begin;
set local search_path = public, extensions;
select plan(14);
select has_schema('platform','platform schema');
select has_schema('identity','identity schema');
select has_schema('portfolio','portfolio schema');
select has_schema('occupancy','occupancy schema');
select has_table('platform','tenants','tenants table');
select has_table('identity','memberships','memberships table');
select has_table('identity','context_grants','context grants table');
select has_table('portfolio','properties','properties table');
select has_table('portfolio','buildings','buildings table');
select has_table('portfolio','units','units table');
select has_table('portfolio','ownerships','ownerships table');
select has_table('occupancy','occupancies','occupancies table');
select has_table('occupancy','leases','leases table');
select has_table('occupancy','cost_responsibilities','cost responsibilities table');
select * from finish();
rollback;
