begin;
set local search_path = public, extensions;
select plan(18);
select has_schema('finance','finance schema');
select has_schema('billing','billing schema');
select has_schema('payments','payments schema');
select has_table('finance','accounts','accounts table');
select has_table('finance','journals','journals table');
select has_table('finance','journal_entries','journal entries table');
select has_table('finance','allocation_runs','allocation runs table');
select has_table('finance','allocation_items','allocation items table');
select has_table('billing','invoices','invoices table');
select has_table('billing','receivables','receivables table');
select has_table('payments','bank_transactions','bank transactions table');
select has_table('payments','reconciliation_matches','reconciliation table');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='finance' and c.relname='journals'),'journals RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='finance' and c.relname='allocation_items'),'allocation items RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='billing' and c.relname='invoices'),'invoices RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='billing' and c.relname='receivables'),'receivables RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='payments' and c.relname='bank_transactions'),'bank transactions RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='payments' and c.relname='reconciliation_matches'),'reconciliation RLS');
select * from finish();
rollback;
