begin;
set local search_path = public, extensions;
select plan(35);
select has_schema('utilities','utilities schema');
select has_table('utilities','providers','providers table');
select has_table('utilities','supply_contracts','supply contracts table');
select has_table('utilities','provider_invoices','provider invoices table');
select has_table('utilities','provider_invoice_lines','provider invoice lines table');
select has_table('utilities','ocr_extractions','OCR extractions table');
select has_table('utilities','ocr_field_candidates','OCR candidates table');
select has_table('utilities','meters','meters table');
select has_table('utilities','meter_readings','meter readings table');
select has_table('utilities','consumption_periods','consumption periods table');
select has_table('utilities','invoice_meter_links','invoice meter links table');
select has_table('utilities','utility_comparisons','utility comparisons table');
select has_table('utilities','utility_anomalies','utility anomalies table');
select has_table('utilities','ingestion_sources','ingestion sources table');
select has_table('utilities','ingestion_runs','ingestion runs table');
select has_table('utilities','ingestion_documents','ingestion documents table');
select has_table('utilities','review_tasks','review tasks table');
select has_table('utilities','review_decisions','review decisions table');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='utilities' and c.relname='providers'),'providers RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='utilities' and c.relname='supply_contracts'),'contracts RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='utilities' and c.relname='provider_invoices'),'provider invoices RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='utilities' and c.relname='provider_invoice_lines'),'provider invoice lines RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='utilities' and c.relname='ocr_extractions'),'OCR extractions RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='utilities' and c.relname='ocr_field_candidates'),'OCR candidates RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='utilities' and c.relname='meters'),'meters RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='utilities' and c.relname='meter_readings'),'meter readings RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='utilities' and c.relname='consumption_periods'),'consumption RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='utilities' and c.relname='invoice_meter_links'),'invoice meter links RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='utilities' and c.relname='utility_comparisons'),'comparisons RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='utilities' and c.relname='utility_anomalies'),'anomalies RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='utilities' and c.relname='ingestion_sources'),'ingestion sources RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='utilities' and c.relname='ingestion_runs'),'ingestion runs RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='utilities' and c.relname='ingestion_documents'),'ingestion documents RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='utilities' and c.relname='review_tasks'),'review tasks RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='utilities' and c.relname='review_decisions'),'review decisions RLS');
select * from finish();
rollback;
