begin;
set local search_path = public, extensions;
select plan(42);
select has_schema('assets','assets schema');
select has_schema('maintenance','maintenance schema');
select has_table('assets','asset_categories','asset categories table');
select has_table('assets','assets','assets table');
select has_table('assets','asset_components','asset components table');
select has_table('assets','asset_warranties','asset warranties table');
select has_table('assets','asset_documents','asset documents table');
select has_table('assets','asset_history','asset history table');
select has_table('maintenance','maintenance_plans','maintenance plans table');
select has_table('maintenance','work_orders','work orders table');
select has_table('maintenance','work_order_checklist_items','checklist table');
select has_table('maintenance','work_order_events','work order events table');
select has_table('maintenance','vendors','vendors table');
select has_table('maintenance','vendor_contracts','vendor contracts table');
select has_table('maintenance','work_order_assignments','assignments table');
select has_table('maintenance','vendor_quotes','quotes table');
select has_table('maintenance','purchase_orders','purchase orders table');
select has_table('maintenance','sla_measurements','SLA table');
select has_table('maintenance','tickets','tickets table');
select has_table('maintenance','ticket_work_orders','ticket work orders table');
select has_table('maintenance','work_order_costs','work order costs table');
select has_table('maintenance','attachments','attachments table');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='assets' and c.relname='asset_categories'),'asset categories RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='assets' and c.relname='assets'),'assets RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='assets' and c.relname='asset_components'),'components RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='assets' and c.relname='asset_warranties'),'warranties RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='assets' and c.relname='asset_documents'),'asset documents RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='assets' and c.relname='asset_history'),'asset history RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='maintenance' and c.relname='maintenance_plans'),'plans RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='maintenance' and c.relname='work_orders'),'work orders RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='maintenance' and c.relname='work_order_checklist_items'),'checklist RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='maintenance' and c.relname='work_order_events'),'events RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='maintenance' and c.relname='vendors'),'vendors RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='maintenance' and c.relname='vendor_contracts'),'contracts RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='maintenance' and c.relname='work_order_assignments'),'assignments RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='maintenance' and c.relname='vendor_quotes'),'quotes RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='maintenance' and c.relname='purchase_orders'),'purchase orders RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='maintenance' and c.relname='sla_measurements'),'SLA RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='maintenance' and c.relname='tickets'),'tickets RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='maintenance' and c.relname='ticket_work_orders'),'ticket links RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='maintenance' and c.relname='work_order_costs'),'costs RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='maintenance' and c.relname='attachments'),'attachments RLS');
select * from finish();
rollback;
