begin;
set local search_path = public, extensions;
select plan(75);
select has_schema('governance','governance schema');
select has_schema('communications','communications schema');
select has_schema('documents','documents schema');
select has_schema('migration_hub','migration hub schema');
select has_schema('audit','audit schema');
select has_table('governance','meetings','meetings');
select has_table('governance','agenda_items','agenda');
select has_table('governance','eligibility_snapshots','eligibility');
select has_table('governance','attendance','attendance');
select has_table('governance','votes','votes');
select has_table('governance','vote_options','vote options');
select has_table('governance','ballots','ballots');
select has_table('governance','resolutions','resolutions');
select has_table('governance','minutes','minutes');
select has_table('communications','channels','channels');
select has_table('communications','channel_members','channel members');
select has_table('communications','posts','posts');
select has_table('communications','comments','comments');
select has_table('communications','reactions','reactions');
select has_table('communications','polls','polls');
select has_table('communications','poll_options','poll options');
select has_table('communications','poll_responses','poll responses');
select has_table('communications','notifications','notifications');
select has_table('communications','notification_preferences','notification preferences');
select has_table('documents','folders','folders');
select has_table('documents','documents','documents');
select has_table('documents','document_versions','document versions');
select has_table('documents','document_links','document links');
select has_table('documents','retention_policies','retention policies');
select has_table('documents','access_events','access events');
select has_table('documents','legal_records','legal records');
select has_table('migration_hub','projects','migration projects');
select has_table('migration_hub','field_mappings','field mappings');
select has_table('migration_hub','import_batches','import batches');
select has_table('migration_hub','staged_records','staged records');
select has_table('migration_hub','validation_results','validation results');
select has_table('migration_hub','reconciliation_runs','reconciliation runs');
select has_table('migration_hub','reconciliation_items','reconciliation items');
select has_table('migration_hub','cutovers','cutovers');
select has_table('audit','events','audit events');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='governance' and c.relname='meetings'),'meetings RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='governance' and c.relname='agenda_items'),'agenda RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='governance' and c.relname='eligibility_snapshots'),'eligibility RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='governance' and c.relname='attendance'),'attendance RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='governance' and c.relname='votes'),'votes RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='governance' and c.relname='vote_options'),'vote options RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='governance' and c.relname='ballots'),'ballots RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='governance' and c.relname='resolutions'),'resolutions RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='governance' and c.relname='minutes'),'minutes RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='communications' and c.relname='channels'),'channels RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='communications' and c.relname='channel_members'),'channel members RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='communications' and c.relname='posts'),'posts RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='communications' and c.relname='comments'),'comments RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='communications' and c.relname='reactions'),'reactions RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='communications' and c.relname='polls'),'polls RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='communications' and c.relname='poll_options'),'poll options RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='communications' and c.relname='poll_responses'),'poll responses RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='communications' and c.relname='notifications'),'notifications RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='communications' and c.relname='notification_preferences'),'preferences RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='documents' and c.relname='folders'),'folders RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='documents' and c.relname='documents'),'documents RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='documents' and c.relname='document_versions'),'versions RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='documents' and c.relname='document_links'),'links RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='documents' and c.relname='retention_policies'),'retention RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='documents' and c.relname='access_events'),'access events RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='documents' and c.relname='legal_records'),'legal records RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='migration_hub' and c.relname='projects'),'projects RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='migration_hub' and c.relname='field_mappings'),'mappings RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='migration_hub' and c.relname='import_batches'),'batches RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='migration_hub' and c.relname='staged_records'),'records RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='migration_hub' and c.relname='validation_results'),'validations RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='migration_hub' and c.relname='reconciliation_runs'),'reconciliation runs RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='migration_hub' and c.relname='reconciliation_items'),'reconciliation items RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='migration_hub' and c.relname='cutovers'),'cutovers RLS');
select ok((select relrowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='audit' and c.relname='events'),'audit RLS');
select * from finish();
rollback;
