begin;
select plan(22);
select ok(to_regprocedure('payments.get_customer_payments(uuid,text,text,text,date,date,integer,integer,uuid)') is not null,'payments RPC exists');
select ok(has_function_privilege('authenticated','payments.get_customer_payments(uuid,text,text,text,date,date,integer,integer,uuid)','EXECUTE'),'authenticated may execute payments RPC');
select ok(not has_function_privilege('anon','payments.get_customer_payments(uuid,text,text,text,date,date,integer,integer,uuid)','EXECUTE'),'anonymous payments execution is denied');
select ok(exists(select 1 from identity.permissions where code='payments.reconciliation.read'),'payments read permission exists');
select ok(exists(select 1 from pg_trigger where tgname='reconciliation_integrity_protect' and tgenabled='O'),'reconciliation integrity trigger is enabled');
select ok((select prorettype='jsonb'::regtype from pg_proc where oid='payments.get_customer_payments(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'RPC returns jsonb');
select ok((select provolatile='s' from pg_proc where oid='payments.get_customer_payments(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'RPC is read-only stable');
select ok((select prosecdef from pg_proc where oid='payments.get_customer_payments(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'RPC owns its authorization boundary');
select ok(position('auth.uid() is null' in pg_get_functiondef('payments.get_customer_payments(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'RPC rejects unauthenticated callers');
select ok(position($needle$auth.jwt()->>'aal'$needle$ in pg_get_functiondef('payments.get_customer_payments(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'RPC requires AAL2');
select ok(position("p.code='payments.reconciliation.read'" in pg_get_functiondef('payments.get_customer_payments(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'RPC requires explicit permission');
select ok(position("e.entitlement_key='module.payments'" in pg_get_functiondef('payments.get_customer_payments(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'RPC requires effective entitlement');
select ok(position("l.status='active'" in pg_get_functiondef('payments.get_customer_payments(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'tenant visibility requires active lease');
select ok(position('p.payer_party_id=v_party' in pg_get_functiondef('payments.get_customer_payments(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'tenant visibility requires mapped payer party');
select ok(position('o.party_id=v_party' in pg_get_functiondef('payments.get_customer_payments(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'owner visibility requires current ownership');
select ok(position('iban_encrypted' in pg_get_functiondef('payments.get_customer_payments(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))=0,'RPC never projects encrypted IBAN');
select ok(position('raw_snapshot' in pg_get_functiondef('payments.get_customer_payments(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))=0,'RPC never projects raw bank snapshots');
select ok(position('remittance_text' in pg_get_functiondef('payments.get_customer_payments(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))=0,'RPC never projects remittance text');
select ok(position('bank_transaction_overallocated' in pg_get_functiondef('payments.protect_confirmed_reconciliation()'::regprocedure))>0,'bank transaction over-allocation is blocked');
select ok(position('payment_overallocated' in pg_get_functiondef('payments.protect_confirmed_reconciliation()'::regprocedure))>0,'payment over-allocation is blocked');
select ok(position('receivable_overallocated' in pg_get_functiondef('payments.protect_confirmed_reconciliation()'::regprocedure))>0,'receivable over-allocation is blocked');
select ok(position('currency_mismatch' in pg_get_functiondef('payments.protect_confirmed_reconciliation()'::regprocedure))>0,'currency mismatch is blocked');
select * from finish();
rollback;
