begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select plan(31);
select ok(exists(select 1 from identity.permissions where code='finance.allocations.read'),'allocation read permission exists');
select ok(exists(select 1 from pg_proc where oid='finance.get_customer_allocations(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'allocation RPC exists');
select ok((select prorettype='jsonb'::regtype from pg_proc where oid='finance.get_customer_allocations(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'RPC returns jsonb');
select ok((select provolatile='s' from pg_proc where oid='finance.get_customer_allocations(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'RPC is read-only stable');
select ok((select prosecdef from pg_proc where oid='finance.get_customer_allocations(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'RPC owns authorization boundary');
select ok(position('auth.uid() is null' in pg_get_functiondef('finance.get_customer_allocations(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'RPC rejects unauthenticated callers');
select ok(position($needle$auth.jwt()->>'aal'$needle$ in pg_get_functiondef('finance.get_customer_allocations(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'RPC requires AAL2');
select ok(position($needle$p.code='finance.allocations.read'$needle$ in pg_get_functiondef('finance.get_customer_allocations(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'RPC requires permission');
select ok(position($needle$e.entitlement_key='module.accounting'$needle$ in pg_get_functiondef('finance.get_customer_allocations(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'RPC requires accounting entitlement');
select ok(position($needle$e.override_expires_at>statement_timestamp()$needle$ in pg_get_functiondef('finance.get_customer_allocations(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'expired overrides ignored');
select ok(position($needle$m.status='active'$needle$ in pg_get_functiondef('finance.get_customer_allocations(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'membership active');
select ok(position('m.starts_at<=statement_timestamp()' in pg_get_functiondef('finance.get_customer_allocations(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'membership time enforced');
select ok(position('g.starts_at<=statement_timestamp()' in pg_get_functiondef('finance.get_customer_allocations(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'context time enforced');
select ok(position('o.party_id=v_party' in pg_get_functiondef('finance.get_customer_allocations(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'owner ownership required');
select ok(position($needle$l.status='active'$needle$ in pg_get_functiondef('finance.get_customer_allocations(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'tenant active lease required');
select ok(position('a.responsible_party_id=v_party' in pg_get_functiondef('finance.get_customer_allocations(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'tenant mapped party required');
select ok(position($needle$in ('owner','shared')$needle$ in pg_get_functiondef('finance.get_customer_allocations(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'owner only owner/shared liabilities');
select ok(position('not v_resident or exists' in pg_get_functiondef('finance.get_customer_allocations(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'resident rules, runs, and summaries require visible unit liabilities');
select ok(position($needle$p_view not in ('runs','rules','lines')$needle$ in pg_get_functiondef('finance.get_customer_allocations(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'view allow-list explicit');
select ok(position('p_limit>100' in pg_get_functiondef('finance.get_customer_allocations(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'pagination bounded');
select ok(exists(select 1 from pg_trigger where tgname='allocation_inputs_integrity' and tgenabled='O'),'input trigger enabled');
select ok(exists(select 1 from pg_trigger where tgname='allocation_items_integrity' and tgenabled='O'),'item trigger enabled');
select ok(position('final_allocation_children_are_immutable' in pg_get_functiondef('finance.protect_allocation_children()'::regprocedure))>0,'final children immutable');
select ok(position('allocation_source_currency_mismatch' in pg_get_functiondef('finance.protect_allocation_children()'::regprocedure))>0,'currency mismatch blocked');
select ok(position('allocation_source_amount_mismatch' in pg_get_functiondef('finance.protect_allocation_children()'::regprocedure))>0,'source amount mismatch blocked');
select ok(position('allocation_input_overallocated' in pg_get_functiondef('finance.protect_allocation_children()'::regprocedure))>0,'over-allocation blocked');
select ok(position('allocation_rule_invalid_or_expired' in pg_get_functiondef('finance.protect_allocation_children()'::regprocedure))>0,'expired rule blocked');
select ok(position('allocation_ownership_invalid' in pg_get_functiondef('finance.protect_allocation_children()'::regprocedure))>0,'invalid ownership blocked');
select ok(position('allocation_lease_invalid' in pg_get_functiondef('finance.protect_allocation_children()'::regprocedure))>0,'invalid lease blocked');
select ok(position('allocation_explanation_incomplete' in pg_get_functiondef('finance.protect_allocation_children()'::regprocedure))>0,'explanation mandatory');
select ok(not has_function_privilege('anon','finance.get_customer_allocations(uuid,text,text,text,text,date,date,integer,integer,uuid)','EXECUTE'),'anon cannot execute RPC');
select * from finish();
rollback;
