begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select plan(35);
select ok(exists(select 1 from identity.permissions where code='utilities.metering.read'),'utility permission exists');
select ok(exists(select 1 from pg_proc where oid='utilities.get_customer_utilities(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'utility RPC exists');
select ok((select prorettype='jsonb'::regtype from pg_proc where oid='utilities.get_customer_utilities(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'RPC returns jsonb');
select ok((select provolatile='s' from pg_proc where oid='utilities.get_customer_utilities(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'RPC is stable');
select ok((select prosecdef from pg_proc where oid='utilities.get_customer_utilities(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'RPC owns authorization');
select ok(position('auth.uid() is null' in pg_get_functiondef('utilities.get_customer_utilities(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'unauthorized rejected');
select ok(position($n$auth.jwt()->>'aal'$n$ in pg_get_functiondef('utilities.get_customer_utilities(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'AAL2 required');
select ok(position($n$p.code='utilities.metering.read'$n$ in pg_get_functiondef('utilities.get_customer_utilities(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'permission required');
select ok(position($n$e.entitlement_key='module.utilities'$n$ in pg_get_functiondef('utilities.get_customer_utilities(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'entitlement required');
select ok(position('e.override_expires_at>statement_timestamp()' in pg_get_functiondef('utilities.get_customer_utilities(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'expired override ignored');
select ok(position($n$m.status='active'$n$ in pg_get_functiondef('utilities.get_customer_utilities(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'active membership required');
select ok(position('m.starts_at<=statement_timestamp()' in pg_get_functiondef('utilities.get_customer_utilities(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'membership time constrained');
select ok(position('g.starts_at<=statement_timestamp()' in pg_get_functiondef('utilities.get_customer_utilities(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'context time constrained');
select ok(position('o.party_id=v_party' in pg_get_functiondef('utilities.get_customer_utilities(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'owner mapping enforced');
select ok(position($n$l.status='active'$n$ in pg_get_functiondef('utilities.get_customer_utilities(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'tenant active lease enforced');
select ok(position('not v_resident or m.unit_id=v.unit_id' in pg_get_functiondef('utilities.get_customer_utilities(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'resident meter scope restricted');
select ok(position('customer_utility_scope_matches' in pg_get_functiondef('utilities.get_customer_utilities(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'tenant, property, building and unit scopes are exact');
select ok(position($n$p_view not in ('meters','readings','periods','contracts','invoices','comparisons','anomalies')$n$ in pg_get_functiondef('utilities.get_customer_utilities(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'view allow-list enforced');
select ok(position('p_limit>100' in pg_get_functiondef('utilities.get_customer_utilities(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'pagination bounded');
select ok(exists(select 1 from pg_trigger where tgname='meters_integrity' and tgenabled='O'),'meter trigger enabled');
select ok(exists(select 1 from pg_trigger where tgname='meter_readings_integrity' and tgenabled='O'),'reading trigger enabled');
select ok(exists(select 1 from pg_trigger where tgname='consumption_periods_integrity' and tgenabled='O'),'consumption trigger enabled');
select ok(exists(select 1 from pg_trigger where tgname='provider_invoices_scope_integrity' and tgenabled='O'),'invoice scope trigger enabled');
select ok(position('meter_unit_scope_invalid' in pg_get_functiondef('utilities.enforce_metering_integrity()'::regprocedure))>0,'meter unit scope enforced');
select ok(position('reading_outside_meter_lifecycle' in pg_get_functiondef('utilities.enforce_metering_integrity()'::regprocedure))>0,'reading lifecycle enforced');
select ok(position('negative_consumption' in pg_get_functiondef('utilities.enforce_metering_integrity()'::regprocedure))>0,'negative consumption blocked');
select ok(position('consumption_snapshot_is_immutable' in pg_get_functiondef('utilities.enforce_metering_integrity()'::regprocedure))>0,'consumption immutable');
select ok(position('delta_times_multiplier' in pg_get_functiondef('utilities.enforce_metering_integrity()'::regprocedure))>0,'consumption database calculated');
select ok(position('utility_invoice_currency_mismatch' in pg_get_functiondef('utilities.enforce_utility_invoice_scope()'::regprocedure))>0,'currency mismatch blocked');
select ok(position('utility_contract_inactive_or_expired' in pg_get_functiondef('utilities.enforce_utility_invoice_scope()'::regprocedure))>0,'expired contract blocked');
select ok(position('evidence_available' in pg_get_functiondef('utilities.get_customer_utilities(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'safe evidence flag projected');
select ok(position('source_object_path' in pg_get_functiondef('utilities.get_customer_utilities(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'evidence presence evaluated server-side');
select ok(position($n$'read_only',true$n$ in pg_get_functiondef('utilities.get_customer_utilities(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'RPC declares read-only');
select ok(not has_function_privilege('anon','utilities.get_customer_utilities(uuid,text,text,text,text,date,date,integer,integer,uuid)','EXECUTE'),'anon cannot execute');
select ok(has_function_privilege('authenticated','utilities.get_customer_utilities(uuid,text,text,text,text,date,date,integer,integer,uuid)','EXECUTE'),'authenticated can execute gated RPC');
select * from finish();
rollback;
