begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select plan(38);
select ok(exists(select 1 from identity.permissions where code='maintenance.assets.read'),'maintenance permission exists');
select ok(exists(select 1 from pg_proc where oid='maintenance.get_customer_maintenance(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'maintenance RPC exists');
select ok((select prorettype='jsonb'::regtype from pg_proc where oid='maintenance.get_customer_maintenance(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'RPC returns jsonb');
select ok((select provolatile='s' from pg_proc where oid='maintenance.get_customer_maintenance(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'RPC is stable');
select ok((select prosecdef from pg_proc where oid='maintenance.get_customer_maintenance(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'RPC owns authorization');
select ok(position('auth.uid() is null' in pg_get_functiondef('maintenance.get_customer_maintenance(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'unauthorized rejected');
select ok(position($n$auth.jwt()->>'aal'$n$ in pg_get_functiondef('maintenance.get_customer_maintenance(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'AAL2 required');
select ok(position($n$p.code='maintenance.assets.read'$n$ in pg_get_functiondef('maintenance.get_customer_maintenance(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'permission required');
select ok(position($n$e.entitlement_key='module.maintenance'$n$ in pg_get_functiondef('maintenance.get_customer_maintenance(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'entitlement required');
select ok(position('e.override_expires_at>statement_timestamp()' in pg_get_functiondef('maintenance.get_customer_maintenance(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'expired override ignored');
select ok(position($n$m.status='active'$n$ in pg_get_functiondef('maintenance.get_customer_maintenance(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'active membership required');
select ok(position('m.starts_at<=statement_timestamp()' in pg_get_functiondef('maintenance.get_customer_maintenance(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'membership time constrained');
select ok(position('g.starts_at<=statement_timestamp()' in pg_get_functiondef('maintenance.get_customer_maintenance(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'context time constrained');
select ok(position('o.party_id=v_party' in pg_get_functiondef('maintenance.get_customer_maintenance(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'owner mapping enforced');
select ok(position($n$l.status='active'$n$ in pg_get_functiondef('maintenance.get_customer_maintenance(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'tenant active lease enforced');
select ok(position('not v_resident or a.unit_id=v.unit_id' in pg_get_functiondef('maintenance.get_customer_maintenance(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'resident asset scope restricted');
select ok(position('customer_maintenance_scope_matches' in pg_get_functiondef('maintenance.get_customer_maintenance(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'exact context scopes enforced');
select ok(position($n$p_view not in ('assets','components','plans','work_orders','tasks','vendors','sla','costs','history')$n$ in pg_get_functiondef('maintenance.get_customer_maintenance(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'view allow-list enforced');
select ok(position('p_limit>100' in pg_get_functiondef('maintenance.get_customer_maintenance(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'pagination bounded');
select ok(exists(select 1 from pg_trigger where tgname='a_customer_asset_integrity' and tgenabled='O'),'asset integrity trigger enabled');
select ok(exists(select 1 from pg_trigger where tgname='a_customer_work_order_integrity' and tgenabled='O'),'work order integrity trigger enabled');
select ok(exists(select 1 from pg_trigger where tgname='a_customer_assignment_integrity' and tgenabled='O'),'assignment integrity trigger enabled');
select ok(exists(select 1 from pg_trigger where tgname='a_customer_cost_integrity' and tgenabled='O'),'cost integrity trigger enabled');
select ok(exists(select 1 from pg_trigger where tgname='a_customer_asset_history_integrity' and tgenabled='O'),'history integrity trigger enabled');
select ok(position('asset_unit_scope_invalid' in pg_get_functiondef('maintenance.enforce_customer_maintenance_integrity()'::regprocedure))>0,'asset unit relation enforced');
select ok(position('work_order_asset_scope_invalid' in pg_get_functiondef('maintenance.enforce_customer_maintenance_integrity()'::regprocedure))>0,'work order asset relation enforced');
select ok(position('assignment_contract_scope_invalid' in pg_get_functiondef('maintenance.enforce_customer_maintenance_integrity()'::regprocedure))>0,'vendor contract relation enforced');
select ok(position('work_order_cost_invoice_invalid' in pg_get_functiondef('maintenance.enforce_customer_maintenance_integrity()'::regprocedure))>0,'invoice relation enforced');
select ok(position('work_order_cost_journal_invalid' in pg_get_functiondef('maintenance.enforce_customer_maintenance_integrity()'::regprocedure))>0,'journal relation enforced');
select ok(position('final_work_order_is_immutable' in pg_get_functiondef('maintenance.enforce_customer_maintenance_integrity()'::regprocedure))>0,'final work orders immutable');
select ok(position('work_order_cost_snapshot_is_immutable' in pg_get_functiondef('maintenance.enforce_customer_maintenance_integrity()'::regprocedure))>0,'cost snapshots immutable');
select ok(position('asset_history_is_append_only' in pg_get_functiondef('maintenance.enforce_customer_maintenance_integrity()'::regprocedure))>0,'asset history append only');
select ok(exists(select 1 from pg_indexes where schemaname='maintenance' and indexname='work_orders_active_plan_asset_unique'),'duplicate active planned work order blocked');
select ok(exists(select 1 from pg_indexes where schemaname='maintenance' and indexname='work_orders_active_ad_hoc_asset_title_unique'),'duplicate active ad hoc work order blocked');
select ok(position($n$'read_only',true$n$ in pg_get_functiondef('maintenance.get_customer_maintenance(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'RPC declares read-only');
select ok(not has_function_privilege('anon','maintenance.get_customer_maintenance(uuid,text,text,text,text,date,date,integer,integer,uuid)','EXECUTE'),'anon cannot execute');
select ok(has_function_privilege('authenticated','maintenance.get_customer_maintenance(uuid,text,text,text,text,date,date,integer,integer,uuid)','EXECUTE'),'authenticated can execute gated RPC');
select ok(not has_table_privilege('authenticated','assets.assets','SELECT') and not has_table_privilege('authenticated','maintenance.attachments','SELECT'),'raw asset and maintenance tables cannot bypass safe RPC');
select * from finish();
rollback;
