begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select plan(38);
select ok(exists(select 1 from identity.permissions where code='governance.meetings.read'),'governance permission exists');
select ok(exists(select 1 from pg_proc where oid='governance.get_customer_governance(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'governance RPC exists');
select ok((select prorettype='jsonb'::regtype from pg_proc where oid='governance.get_customer_governance(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'RPC returns jsonb');
select ok((select provolatile='s' from pg_proc where oid='governance.get_customer_governance(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'RPC is stable');
select ok((select prosecdef from pg_proc where oid='governance.get_customer_governance(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'RPC owns authorization');
select ok(position('auth.uid() is null' in pg_get_functiondef('governance.get_customer_governance(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'unauthorized rejected');
select ok(position($n$auth.jwt()->>'aal'$n$ in pg_get_functiondef('governance.get_customer_governance(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'AAL2 required');
select ok(position($n$p.code='governance.meetings.read'$n$ in pg_get_functiondef('governance.get_customer_governance(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'permission required');
select ok(position($n$e.entitlement_key='module.governance'$n$ in pg_get_functiondef('governance.get_customer_governance(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'entitlement required');
select ok(position('e.override_expires_at>statement_timestamp()' in pg_get_functiondef('governance.get_customer_governance(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'expired override ignored');
select ok(position($n$m.status='active'$n$ in pg_get_functiondef('governance.get_customer_governance(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'active membership required');
select ok(position('m.starts_at<=statement_timestamp()' in pg_get_functiondef('governance.get_customer_governance(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'membership time constrained');
select ok(position('g.starts_at<=statement_timestamp()' in pg_get_functiondef('governance.get_customer_governance(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'context time constrained');
select ok(position('o.party_id=v_party' in pg_get_functiondef('governance.get_customer_governance(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'owner mapping enforced');
select ok(position($n$l.status='active'$n$ in pg_get_functiondef('governance.get_customer_governance(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'tenant active lease enforced');
select ok(position('customer_governance_scope_matches' in pg_get_functiondef('governance.get_customer_governance(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'exact context scope enforced');
select ok(position($n$p_view not in ('meetings','agenda','invitations','attendance','quorum','proxies','votes','resolutions','minutes','documents','history')$n$ in pg_get_functiondef('governance.get_customer_governance(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'view allow-list enforced');
select ok(position('p_limit>100' in pg_get_functiondef('governance.get_customer_governance(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'pagination bounded');
select ok(exists(select 1 from pg_trigger where tgname='customer_eligibility_integrity' and tgenabled='O'),'eligibility integrity enabled');
select ok(exists(select 1 from pg_trigger where tgname='customer_ballot_integrity' and tgenabled='O'),'ballot integrity enabled');
select ok(exists(select 1 from pg_trigger where tgname='customer_proxy_integrity' and tgenabled='O'),'proxy integrity enabled');
select ok(exists(select 1 from pg_trigger where tgname='customer_resolution_integrity' and tgenabled='O'),'resolution integrity enabled');
select ok(exists(select 1 from pg_trigger where tgname='customer_minutes_integrity' and tgenabled='O'),'minutes integrity enabled');
select ok(exists(select 1 from pg_trigger where tgname='customer_meeting_history_integrity' and tgenabled='O'),'history integrity enabled');
select ok(position('eligibility_snapshot_is_immutable' in pg_get_functiondef('governance.enforce_customer_governance_integrity()'::regprocedure))>0,'eligibility snapshots immutable');
select ok(position('ballot_eligibility_or_time_invalid' in pg_get_functiondef('governance.enforce_customer_governance_integrity()'::regprocedure))>0,'ballot eligibility and timing enforced');
select ok(position('overlapping_active_proxy' in pg_get_functiondef('governance.enforce_customer_governance_integrity()'::regprocedure))>0,'overlapping proxies rejected');
select ok(position('adopted_resolution_is_immutable' in pg_get_functiondef('governance.enforce_customer_governance_integrity()'::regprocedure))>0,'adopted resolutions immutable');
select ok(position('approved_minutes_are_immutable' in pg_get_functiondef('governance.enforce_customer_governance_integrity()'::regprocedure))>0,'approved minutes immutable');
select ok(position('meeting_history_is_append_only' in pg_get_functiondef('governance.enforce_customer_governance_integrity()'::regprocedure))>0,'history append only');
select ok(position('jsonb_object_agg' in pg_get_functiondef('governance.get_customer_governance(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'vote results aggregate by option');
select ok(position('not v_tenant' in pg_get_functiondef('governance.get_customer_governance(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'tenant private views denied');
select ok(position($n$'secret_ballots_redacted',true$n$ in pg_get_functiondef('governance.get_customer_governance(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'secret ballot redaction declared');
select ok(position($n$'read_only',true$n$ in pg_get_functiondef('governance.get_customer_governance(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'RPC declares read-only');
select ok(not has_function_privilege('anon','governance.get_customer_governance(uuid,text,text,text,date,date,integer,integer,uuid)','EXECUTE'),'anon cannot execute');
select ok(has_function_privilege('authenticated','governance.get_customer_governance(uuid,text,text,text,date,date,integer,integer,uuid)','EXECUTE'),'authenticated can execute gated RPC');
select ok(not has_table_privilege('authenticated','governance.ballots','SELECT'),'raw ballots cannot bypass aggregate RPC');
select ok(not has_table_privilege('authenticated','governance.proxies','SELECT'),'raw proxies cannot bypass redacted RPC');
select * from finish();
rollback;
