begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select plan(39);
select ok(exists(select 1 from identity.permissions where code='communications.feed.read'),'communications permission exists');
select has_table('communications','communication_links','typed communication links exist');
select ok(exists(select 1 from pg_proc where oid='communications.get_customer_communications(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'communications RPC exists');
select ok((select prorettype='jsonb'::regtype from pg_proc where oid='communications.get_customer_communications(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'RPC returns jsonb');
select ok((select provolatile='s' from pg_proc where oid='communications.get_customer_communications(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'RPC is stable');
select ok((select prosecdef from pg_proc where oid='communications.get_customer_communications(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'RPC owns authorization');
select ok(position('auth.uid() is null' in pg_get_functiondef('communications.get_customer_communications(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'unauthorized rejected');
select ok(position($n$auth.jwt()->>'aal'$n$ in pg_get_functiondef('communications.get_customer_communications(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'AAL2 required');
select ok(position($n$p.code='communications.feed.read'$n$ in pg_get_functiondef('communications.get_customer_communications(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'permission required');
select ok(position($n$e.entitlement_key='module.communications'$n$ in pg_get_functiondef('communications.get_customer_communications(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'entitlement required');
select ok(position('e.override_expires_at>statement_timestamp()' in pg_get_functiondef('communications.get_customer_communications(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'expired override ignored');
select ok(position($n$m.status='active'$n$ in pg_get_functiondef('communications.get_customer_communications(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'active membership required');
select ok(position('m.starts_at<=statement_timestamp()' in pg_get_functiondef('communications.get_customer_communications(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'membership time constrained');
select ok(position('g.starts_at<=statement_timestamp()' in pg_get_functiondef('communications.get_customer_communications(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'context time constrained');
select ok(position('o.party_id=v_party' in pg_get_functiondef('communications.get_customer_communications(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'owner mapping enforced');
select ok(position($n$l.status='active'$n$ in pg_get_functiondef('communications.get_customer_communications(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'tenant active lease enforced');
select ok(position('customer_channel_scope_matches' in pg_get_functiondef('communications.get_customer_communications(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'exact context scope enforced');
select ok(position('communications.channel_members' in pg_get_functiondef('communications.get_customer_communications(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'private channel membership enforced');
select ok(position('p_limit>100' in pg_get_functiondef('communications.get_customer_communications(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'pagination bounded');
select ok(exists(select 1 from pg_trigger where tgname='customer_poll_response_integrity' and tgenabled='O'),'poll response integrity enabled');
select ok(exists(select 1 from pg_trigger where tgname='customer_poll_final_integrity' and tgenabled='O'),'poll final integrity enabled');
select ok(exists(select 1 from pg_trigger where tgname='customer_comment_integrity' and tgenabled='O'),'comment integrity enabled');
select ok(exists(select 1 from pg_trigger where tgname='customer_communication_link_integrity' and tgenabled='O'),'link integrity enabled');
select ok(position('poll_response_is_immutable' in pg_get_functiondef('communications.enforce_customer_communications_integrity()'::regprocedure))>0,'poll responses are insert only');
select ok(position('poll_is_not_open' in pg_get_functiondef('communications.enforce_customer_communications_integrity()'::regprocedure))>0,'poll time window enforced');
select ok(position('poll_option_mismatch' in pg_get_functiondef('communications.enforce_customer_communications_integrity()'::regprocedure))>0,'poll option validated');
select ok(position('poll_channel_membership_required' in pg_get_functiondef('communications.enforce_customer_communications_integrity()'::regprocedure))>0,'poll membership enforced');
select ok(position('single_choice_poll_allows_one_response' in pg_get_functiondef('communications.enforce_customer_communications_integrity()'::regprocedure))>0,'duplicate response rejected');
select ok(position('final_poll_is_immutable' in pg_get_functiondef('communications.enforce_customer_communications_integrity()'::regprocedure))>0,'final poll immutable');
select ok(position('post_comments_are_closed' in pg_get_functiondef('communications.enforce_customer_communications_integrity()'::regprocedure))>0,'closed post comment rejected');
select ok(position('communication_link_is_immutable' in pg_get_functiondef('communications.enforce_customer_communications_integrity()'::regprocedure))>0,'links are insert only');
select ok(position('jsonb_object_agg' in pg_get_functiondef('communications.get_customer_communications(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'poll results are aggregated');
select ok(position($n$'anonymous_polls_aggregated',true$n$ in regexp_replace(pg_get_functiondef('communications.get_customer_communications(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'\s+','','g'))>0,'anonymous response redaction declared');
select ok(position($n$'read_only',true$n$ in regexp_replace(pg_get_functiondef('communications.get_customer_communications(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'\s+','','g'))>0,'RPC declares read-only');
select ok(position('n.membership_id=x.membership_key' in regexp_replace(pg_get_functiondef('communications.get_customer_communications(uuid,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'\s+','','g'))>0,'notifications limited to current member');
select ok(not has_function_privilege('anon','communications.get_customer_communications(uuid,text,text,text,date,date,integer,integer,uuid)','EXECUTE'),'anon cannot execute');
select ok(has_function_privilege('authenticated','communications.get_customer_communications(uuid,text,text,text,date,date,integer,integer,uuid)','EXECUTE'),'authenticated can execute gated RPC');
select ok(not has_table_privilege('authenticated','communications.poll_responses','SELECT'),'raw poll responses cannot bypass aggregate RPC');
select ok(not has_table_privilege('authenticated','communications.notifications','SELECT'),'raw notification payload cannot bypass redacted RPC');
select * from finish();
rollback;
