begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select plan(40);
select ok(exists(select 1 from identity.permissions where code='documents.vault.read'),'document permission exists');
select has_table('documents','document_permissions','explicit document grants exist');
select has_table('documents','legal_holds','legal holds exist');
select has_table('documents','retention_records','retention snapshots exist');
select has_table('documents','lifecycle_events','document lifecycle exists');
select ok(exists(select 1 from pg_proc where oid='documents.get_customer_documents(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'document RPC exists');
select ok((select prorettype='jsonb'::regtype from pg_proc where oid='documents.get_customer_documents(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'RPC returns jsonb');
select ok((select provolatile='s' from pg_proc where oid='documents.get_customer_documents(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'RPC is stable');
select ok((select prosecdef from pg_proc where oid='documents.get_customer_documents(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'RPC owns authorization');
select ok(position('auth.uid() is null' in pg_get_functiondef('documents.get_customer_documents(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'unauthorized rejected');
select ok(position($n$auth.jwt()->>'aal'$n$ in pg_get_functiondef('documents.get_customer_documents(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'AAL2 required');
select ok(position($n$p.code='documents.vault.read'$n$ in pg_get_functiondef('documents.get_customer_documents(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'permission required');
select ok(position($n$e.entitlement_key='module.documents'$n$ in pg_get_functiondef('documents.get_customer_documents(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'entitlement required');
select ok(position('e.override_expires_at>statement_timestamp()' in pg_get_functiondef('documents.get_customer_documents(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'expired override ignored');
select ok(position($n$m.status='active'$n$ in pg_get_functiondef('documents.get_customer_documents(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'active membership required');
select ok(position('m.starts_at<=statement_timestamp()' in pg_get_functiondef('documents.get_customer_documents(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'membership time constrained');
select ok(position('g.starts_at<=statement_timestamp()' in pg_get_functiondef('documents.get_customer_documents(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'context time constrained');
select ok(position('o.party_id=v_party' in pg_get_functiondef('documents.get_customer_documents(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'owner mapping enforced');
select ok(position($n$l.status='active'$n$ in pg_get_functiondef('documents.get_customer_documents(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'tenant active lease enforced');
select ok(position('customer_document_scope_matches' in pg_get_functiondef('documents.get_customer_documents(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'context scope enforced');
select ok(position($n$d.classification='public'$n$ in pg_get_functiondef('documents.get_customer_documents(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'tenant public visibility constrained');
select ok(position('documents.document_permissions' in pg_get_functiondef('documents.get_customer_documents(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'explicit grants supported');
select ok(position($n$l.entity_type='portfolio.unit'$n$ in pg_get_functiondef('documents.get_customer_documents(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'owner unit link required');
select ok(position('p_limit>100' in pg_get_functiondef('documents.get_customer_documents(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'pagination bounded');
select ok(exists(select 1 from pg_trigger where tgname='customer_document_link_integrity'and tgenabled='O'),'link integrity enabled');
select ok(exists(select 1 from pg_trigger where tgname='customer_document_integrity'and tgenabled='O'),'document integrity enabled');
select ok(exists(select 1 from pg_trigger where tgname='customer_legal_hold_integrity'and tgenabled='O'),'legal hold integrity enabled');
select ok(exists(select 1 from pg_trigger where tgname='customer_retention_integrity'and tgenabled='O'),'retention integrity enabled');
select ok(exists(select 1 from pg_trigger where tgname='customer_document_lifecycle_integrity'and tgenabled='O'),'lifecycle integrity enabled');
select ok(position('document_link_cross_tenant_or_missing' in pg_get_functiondef('documents.enforce_customer_document_integrity()'::regprocedure))>0,'cross-tenant link rejected');
select ok(position('document_under_legal_hold' in pg_get_functiondef('documents.enforce_customer_document_integrity()'::regprocedure))>0,'legal hold blocks mutation');
select ok(position('published_document_is_immutable' in pg_get_functiondef('documents.enforce_customer_document_integrity()'::regprocedure))>0,'published document immutable');
select ok(position('classification_downgrade_forbidden' in pg_get_functiondef('documents.enforce_customer_document_integrity()'::regprocedure))>0,'classification downgrade rejected');
select ok(position('final_retention_record_is_immutable' in pg_get_functiondef('documents.enforce_customer_document_integrity()'::regprocedure))>0,'retention snapshot immutable');
select ok(position('document_lifecycle_is_append_only' in pg_get_functiondef('documents.enforce_customer_document_integrity()'::regprocedure))>0,'lifecycle append only');
select ok(position($n$'storage_access',false$n$ in regexp_replace(pg_get_functiondef('documents.get_customer_documents(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'\s+','','g'))>0,'storage access disabled');
select ok(position($n$'signed_urls',false$n$ in regexp_replace(pg_get_functiondef('documents.get_customer_documents(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'\s+','','g'))>0,'signed URLs disabled');
select ok(not has_function_privilege('anon','documents.get_customer_documents(uuid,text,text,text,text,date,date,integer,integer,uuid)','EXECUTE'),'anon cannot execute');
select ok(has_function_privilege('authenticated','documents.get_customer_documents(uuid,text,text,text,text,date,date,integer,integer,uuid)','EXECUTE'),'authenticated can execute gated RPC');
select ok(not has_table_privilege('authenticated','documents.document_versions','SELECT'),'raw object paths cannot bypass projection');
select * from finish();
rollback;
