begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select plan(46);
select ok(exists(select 1 from identity.permissions where code='occupancy.registry.read'),'registry permission exists');
select has_table('occupancy','lifecycle_events','registry lifecycle exists');
select ok(exists(select 1 from pg_proc where oid='occupancy.get_customer_registry(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'registry RPC exists');
select ok((select prorettype='jsonb'::regtype from pg_proc where oid='occupancy.get_customer_registry(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'RPC returns jsonb');
select ok((select provolatile='s' from pg_proc where oid='occupancy.get_customer_registry(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'RPC is stable');
select ok((select prosecdef from pg_proc where oid='occupancy.get_customer_registry(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'RPC owns authorization');
select ok(position('auth.uid()is null' in regexp_replace(pg_get_functiondef('occupancy.get_customer_registry(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'\s+','','g'))>0,'unauthorized rejected');
select ok(position($n$auth.jwt()->>'aal'$n$ in pg_get_functiondef('occupancy.get_customer_registry(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'AAL2 required');
select ok(position($n$p.code='occupancy.registry.read'$n$ in pg_get_functiondef('occupancy.get_customer_registry(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'permission required');
select ok(position($n$e.entitlement_key='module.occupancy'$n$ in pg_get_functiondef('occupancy.get_customer_registry(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'entitlement required');
select ok(position('e.override_expires_at>statement_timestamp()' in pg_get_functiondef('occupancy.get_customer_registry(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'expired override ignored');
select ok(position($n$m.status='active'$n$ in pg_get_functiondef('occupancy.get_customer_registry(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'active membership required');
select ok(position('m.starts_at<=statement_timestamp()' in pg_get_functiondef('occupancy.get_customer_registry(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'membership time constrained');
select ok(position('g.starts_at<=statement_timestamp()' in pg_get_functiondef('occupancy.get_customer_registry(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'context time constrained');
select ok(position('mp.valid_from<=statement_timestamp()' in pg_get_functiondef('occupancy.get_customer_registry(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'party mapping time constrained');
select ok(position('o.party_id=v_party' in pg_get_functiondef('occupancy.get_customer_registry(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'owner mapping enforced');
select ok(position($n$l.tenant_party_id=v_party$n$ in pg_get_functiondef('occupancy.get_customer_registry(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'tenant lease enforced');
select ok(position('p_limit>100' in pg_get_functiondef('occupancy.get_customer_registry(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'pagination bounded');
select ok(exists(select 1 from pg_trigger where tgname='customer_ownership_integrity'and tgenabled='O'),'ownership integrity enabled');
select ok(exists(select 1 from pg_trigger where tgname='customer_lease_integrity'and tgenabled='O'),'lease integrity enabled');
select ok(exists(select 1 from pg_trigger where tgname='customer_occupancy_integrity'and tgenabled='O'),'occupancy integrity enabled');
select ok(exists(select 1 from pg_trigger where tgname='customer_occupant_integrity'and tgenabled='O'),'resident integrity enabled');
select ok(exists(select 1 from pg_trigger where tgname='customer_party_mapping_integrity'and tgenabled='O'),'party mapping integrity enabled');
select ok(exists(select 1 from pg_trigger where tgname='customer_occupancy_lifecycle_integrity'and tgenabled='O'),'lifecycle integrity enabled');
select ok(position('ownership_cross_tenant_or_invalid_link' in pg_get_functiondef('occupancy.enforce_customer_registry_integrity()'::regprocedure))>0,'cross-tenant ownership rejected');
select ok(position('ownership_share_exceeds_one' in pg_get_functiondef('occupancy.enforce_customer_registry_integrity()'::regprocedure))>0,'ownership total guarded');
select ok(position('overlapping_party_ownership' in pg_get_functiondef('occupancy.enforce_customer_registry_integrity()'::regprocedure))>0,'overlapping ownership for the same party rejected');
select ok(position('lease_cross_tenant_or_invalid_link' in pg_get_functiondef('occupancy.enforce_customer_registry_integrity()'::regprocedure))>0,'cross-tenant lease rejected');
select ok(position('lease_landlord_ownership_required' in pg_get_functiondef('occupancy.enforce_customer_registry_integrity()'::regprocedure))>0,'landlord ownership required');
select ok(position('overlapping_active_lease' in pg_get_functiondef('occupancy.enforce_customer_registry_integrity()'::regprocedure))>0,'active lease overlap rejected');
select ok(position('invalid_overlapping_occupancy' in pg_get_functiondef('occupancy.enforce_customer_registry_integrity()'::regprocedure))>0,'invalid occupancy overlap rejected');
select ok(position('occupant_outside_active_lease' in pg_get_functiondef('occupancy.enforce_customer_registry_integrity()'::regprocedure))>0,'resident lease period enforced');
select ok(position('party_mapping_cross_tenant_or_invalid' in pg_get_functiondef('occupancy.enforce_customer_registry_integrity()'::regprocedure))>0,'party mapping tenant boundary enforced');
select ok(position('final_ownership_snapshot_is_immutable' in pg_get_functiondef('occupancy.enforce_customer_registry_integrity()'::regprocedure))>0,'final ownership immutable');
select ok(position('final_lease_snapshot_is_immutable' in pg_get_functiondef('occupancy.enforce_customer_registry_integrity()'::regprocedure))>0,'final lease immutable');
select ok(position('final_occupancy_snapshot_is_immutable' in pg_get_functiondef('occupancy.enforce_customer_registry_integrity()'::regprocedure))>0,'final occupancy immutable');
select ok(position('final_party_mapping_is_immutable' in pg_get_functiondef('occupancy.enforce_customer_registry_integrity()'::regprocedure))>0,'final party mapping immutable');
select ok(position('occupancy_lifecycle_is_append_only' in pg_get_functiondef('occupancy.enforce_customer_registry_integrity()'::regprocedure))>0,'lifecycle append only');
select ok(position('occupancy_lifecycle_cross_tenant_or_invalid_link' in pg_get_functiondef('occupancy.enforce_customer_registry_integrity()'::regprocedure))>0,'lifecycle entity tenant boundary enforced');
select ok(position('z.occupancy_id=o.idandz.party_id=v_party' in regexp_replace(pg_get_functiondef('occupancy.get_customer_registry(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'\s+','','g'))>0,'tenant sees only own occupancy rows');
select ok(position('l.starts_on<=o.starts_at::date' in regexp_replace(pg_get_functiondef('occupancy.get_customer_registry(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'\s+','','g'))>0,'tenant occupancy is bounded by active lease period');
select ok(position('receivable_count' in pg_get_functiondef('occupancy.get_customer_registry(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'receivable relationships projected');
select ok(position('meeting_count' in pg_get_functiondef('occupancy.get_customer_registry(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'meeting relationships projected');
select ok(position($n$'pii_redacted',true$n$ in regexp_replace(pg_get_functiondef('occupancy.get_customer_registry(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'\s+','','g'))>0,'PII redaction declared');
select ok(not has_function_privilege('anon','occupancy.get_customer_registry(uuid,text,text,text,text,date,date,integer,integer,uuid)','EXECUTE'),'anon cannot execute');
select ok(has_function_privilege('authenticated','occupancy.get_customer_registry(uuid,text,text,text,text,date,date,integer,integer,uuid)','EXECUTE'),'authenticated can execute gated RPC');
select * from finish();
rollback;
