begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select plan(53);
select has_schema('security_access','security access schema exists');
select has_table('security_access','access_points','access points exist');
select has_table('security_access','credentials','credentials exist');
select has_table('security_access','credential_assignments','credential assignments exist');
select has_table('security_access','visitor_passes','visitor passes exist');
select has_table('security_access','access_events','access events exist');
select has_table('security_access','credential_lifecycle','credential lifecycle exists');
select has_table('security_access','visitor_access_history','visitor history exists');
select ok(exists(select 1 from identity.permissions where code='security.access.read'),'security read permission exists');
select ok(exists(select 1 from pg_proc where oid='security_access.get_customer_security_access(uuid,text,text,text,text,timestamptz,timestamptz,integer,integer,uuid)'::regprocedure),'security RPC exists');
select ok((select prorettype='jsonb'::regtype from pg_proc where oid='security_access.get_customer_security_access(uuid,text,text,text,text,timestamptz,timestamptz,integer,integer,uuid)'::regprocedure),'RPC returns jsonb');
select ok((select provolatile='s' from pg_proc where oid='security_access.get_customer_security_access(uuid,text,text,text,text,timestamptz,timestamptz,integer,integer,uuid)'::regprocedure),'RPC is stable');
select ok((select prosecdef from pg_proc where oid='security_access.get_customer_security_access(uuid,text,text,text,text,timestamptz,timestamptz,integer,integer,uuid)'::regprocedure),'RPC owns authorization');
select ok(position('auth.uid()isnull' in lower(regexp_replace(pg_get_functiondef('security_access.get_customer_security_access(uuid,text,text,text,text,timestamptz,timestamptz,integer,integer,uuid)'::regprocedure),'\s+','','g')))>0,'authentication required');
select ok(position($n$auth.jwt()->>'aal'$n$ in pg_get_functiondef('security_access.get_customer_security_access(uuid,text,text,text,text,timestamptz,timestamptz,integer,integer,uuid)'::regprocedure))>0,'AAL2 required');
select ok(position($n$p.code='security.access.read'$n$ in pg_get_functiondef('security_access.get_customer_security_access(uuid,text,text,text,text,timestamptz,timestamptz,integer,integer,uuid)'::regprocedure))>0,'permission required');
select ok(position($n$e.entitlement_key='module.security'$n$ in pg_get_functiondef('security_access.get_customer_security_access(uuid,text,text,text,text,timestamptz,timestamptz,integer,integer,uuid)'::regprocedure))>0,'security entitlement required');
select ok(position('e.override_expires_at>statement_timestamp()' in pg_get_functiondef('security_access.get_customer_security_access(uuid,text,text,text,text,timestamptz,timestamptz,integer,integer,uuid)'::regprocedure))>0,'expired entitlement override ignored');
select ok(position($n$m.status='active'$n$ in pg_get_functiondef('security_access.get_customer_security_access(uuid,text,text,text,text,timestamptz,timestamptz,integer,integer,uuid)'::regprocedure))>0,'active membership required');
select ok(position('m.starts_at<=statement_timestamp()' in pg_get_functiondef('security_access.get_customer_security_access(uuid,text,text,text,text,timestamptz,timestamptz,integer,integer,uuid)'::regprocedure))>0,'membership time constrained');
select ok(position('g.starts_at<=statement_timestamp()' in pg_get_functiondef('security_access.get_customer_security_access(uuid,text,text,text,text,timestamptz,timestamptz,integer,integer,uuid)'::regprocedure))>0,'context time constrained');
select ok(position('mp.valid_from<=statement_timestamp()' in pg_get_functiondef('security_access.get_customer_security_access(uuid,text,text,text,text,timestamptz,timestamptz,integer,integer,uuid)'::regprocedure))>0,'party mapping time constrained');
select ok(position('security_role_view_denied' in pg_get_functiondef('security_access.get_customer_security_access(uuid,text,text,text,text,timestamptz,timestamptz,integer,integer,uuid)'::regprocedure))>0,'president and censor views constrained');
select ok(position($n$when'owner'then$n$ in pg_get_functiondef('security_access.get_customer_security_access(uuid,text,text,text,text,timestamptz,timestamptz,integer,integer,uuid)'::regprocedure))>0,'owner ownership scope enforced');
select ok(position($n$when'tenant_resident'then$n$ in pg_get_functiondef('security_access.get_customer_security_access(uuid,text,text,text,text,timestamptz,timestamptz,integer,integer,uuid)'::regprocedure))>0,'tenant lease and occupancy scope enforced');
select ok(position('p_limit>100' in pg_get_functiondef('security_access.get_customer_security_access(uuid,text,text,text,text,timestamptz,timestamptz,integer,integer,uuid)'::regprocedure))>0,'pagination bounded');
select ok(position('credential_effective_status' in pg_get_functiondef('security_access.get_customer_security_access(uuid,text,text,text,text,timestamptz,timestamptz,integer,integer,uuid)'::regprocedure))>0,'credential status computed by database');
select ok(position('visitor_effective_status' in pg_get_functiondef('security_access.get_customer_security_access(uuid,text,text,text,text,timestamptz,timestamptz,integer,integer,uuid)'::regprocedure))>0,'visitor status computed by database');
select ok(position('access_period_eligible' in pg_get_functiondef('security_access.get_customer_security_access(uuid,text,text,text,text,timestamptz,timestamptz,integer,integer,uuid)'::regprocedure))>0,'access period eligibility projected');
select ok(position('context_eligible' in pg_get_functiondef('security_access.get_customer_security_access(uuid,text,text,text,text,timestamptz,timestamptz,integer,integer,uuid)'::regprocedure))>0,'context eligibility projected');
select ok(position($n$'credential_data_masked',true$n$ in regexp_replace(pg_get_functiondef('security_access.get_customer_security_access(uuid,text,text,text,text,timestamptz,timestamptz,integer,integer,uuid)'::regprocedure),'\s+','','g'))>0,'credential masking declared');
select ok(position($n$'physical_control',false$n$ in regexp_replace(pg_get_functiondef('security_access.get_customer_security_access(uuid,text,text,text,text,timestamptz,timestamptz,integer,integer,uuid)'::regprocedure),'\s+','','g'))>0,'physical control explicitly disabled');
select ok(exists(select 1 from pg_trigger where tgname='security_access_points_integrity'and tgenabled='O'),'access point integrity enabled');
select ok(exists(select 1 from pg_trigger where tgname='security_credentials_integrity'and tgenabled='O'),'credential integrity enabled');
select ok(exists(select 1 from pg_trigger where tgname='security_assignments_integrity'and tgenabled='O'),'assignment integrity enabled');
select ok(exists(select 1 from pg_trigger where tgname='security_visitors_integrity'and tgenabled='O'),'visitor integrity enabled');
select ok(exists(select 1 from pg_trigger where tgname='security_events_integrity'and tgenabled='O'),'event integrity enabled');
select ok(position('access_point_cross_tenant_or_invalid_scope' in pg_get_functiondef('security_access.enforce_access_integrity()'::regprocedure))>0,'cross tenant access point rejected');
select ok(position('access_point_invalid_unit' in pg_get_functiondef('security_access.enforce_access_integrity()'::regprocedure))>0,'invalid unit rejected');
select ok(position('overlapping_credential_assignment' in pg_get_functiondef('security_access.enforce_access_integrity()'::regprocedure))>0,'overlapping assignment rejected');
select ok(position('expired_party_mapping' in pg_get_functiondef('security_access.enforce_access_integrity()'::regprocedure))>0,'expired credential mapping rejected');
select ok(position('credential_ownership_or_lease_invalid' in pg_get_functiondef('security_access.enforce_access_integrity()'::regprocedure))>0,'invalid credential ownership or lease rejected');
select ok(position('visitor_access_point_out_of_scope' in pg_get_functiondef('security_access.enforce_access_integrity()'::regprocedure))>0,'visitor point scope enforced');
select ok(position('visitor_expired_party_mapping' in pg_get_functiondef('security_access.enforce_access_integrity()'::regprocedure))>0,'visitor mapping period enforced');
select ok(position('visitor_ownership_or_lease_invalid' in pg_get_functiondef('security_access.enforce_access_integrity()'::regprocedure))>0,'visitor ownership or lease enforced');
select ok(position('ineligible_credential_cannot_allow_access' in pg_get_functiondef('security_access.enforce_access_integrity()'::regprocedure))>0,'invalid credential cannot allow access');
select ok(position('visitor_access_outside_invitation' in pg_get_functiondef('security_access.enforce_access_integrity()'::regprocedure))>0,'visitor outside invite cannot allow access');
select ok(position('access_history_is_append_only' in pg_get_functiondef('security_access.enforce_access_integrity()'::regprocedure))>0,'logs and history append only');
select ok(position('final_credential_snapshot_is_immutable' in pg_get_functiondef('security_access.enforce_access_integrity()'::regprocedure))>0,'final credential immutable');
select ok(position('final_visitor_pass_is_immutable' in pg_get_functiondef('security_access.enforce_access_integrity()'::regprocedure))>0,'final visitor pass immutable');
select ok(not has_table_privilege('authenticated','security_access.credentials','SELECT'),'raw credentials unavailable');
select ok(not has_function_privilege('anon','security_access.get_customer_security_access(uuid,text,text,text,text,timestamptz,timestamptz,integer,integer,uuid)','EXECUTE'),'anon cannot execute RPC');
select ok(has_function_privilege('authenticated','security_access.get_customer_security_access(uuid,text,text,text,text,timestamptz,timestamptz,integer,integer,uuid)','EXECUTE'),'authenticated can execute gated RPC');
select * from finish();
rollback;
