begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select plan(40);

select ok(exists(select 1 from identity.permissions where code='maintenance.procurement.read'),'procurement read permission exists');
select ok(not exists(select 1 from identity.roles r where lower(r.code) in ('association_admin','property_manager','president','censor') and not exists(select 1 from identity.role_permissions rp join identity.permissions p on p.id=rp.permission_id where rp.role_id=r.id and p.code='maintenance.procurement.read' and rp.effect='allow')),'every existing approved customer role receives procurement permission');
select ok(exists(select 1 from pg_proc where oid='maintenance.get_customer_procurement(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'procurement RPC exists');
select ok((select prorettype='jsonb'::regtype from pg_proc where oid='maintenance.get_customer_procurement(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'RPC returns jsonb');
select ok((select provolatile='s' from pg_proc where oid='maintenance.get_customer_procurement(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'RPC is stable');
select ok((select prosecdef from pg_proc where oid='maintenance.get_customer_procurement(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'RPC owns authorization');
select ok(position('auth.uid() is null' in pg_get_functiondef('maintenance.get_customer_procurement(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'authentication required');
select ok(position($n$auth.jwt()->>'aal'$n$ in pg_get_functiondef('maintenance.get_customer_procurement(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'AAL2 required');
select ok(position($n$m.status='active'$n$ in pg_get_functiondef('maintenance.get_customer_procurement(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'active membership required');
select ok(position('m.starts_at<=statement_timestamp()' in pg_get_functiondef('maintenance.get_customer_procurement(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'membership time constrained');
select ok(position($n$lower(v.role_code) not in ('association_admin','property_manager','president','censor')$n$ in pg_get_functiondef('maintenance.get_customer_procurement(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'procurement role allow-list enforced');
select ok(position($n$p.code='maintenance.procurement.read'$n$ in pg_get_functiondef('maintenance.get_customer_procurement(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'explicit permission required');
select ok(position($n$e.entitlement_key='module.maintenance'$n$ in pg_get_functiondef('maintenance.get_customer_procurement(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'maintenance entitlement required');
select ok(position('e.override_expires_at>statement_timestamp()' in pg_get_functiondef('maintenance.get_customer_procurement(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'expired entitlement override ignored');
select ok(position($n$w.lifecycle_status='ACTIVE'$n$ in pg_get_functiondef('maintenance.get_customer_procurement(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'active workspace required');
select ok(position($n$p_view not in ('vendors','contracts','quotes','purchase_orders','sla')$n$ in pg_get_functiondef('maintenance.get_customer_procurement(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'view allow-list enforced');
select ok(position('p_limit>100' in pg_get_functiondef('maintenance.get_customer_procurement(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'pagination bounded');
select ok(position($n$p_currency !~ '^[A-Z]{3}$'$n$ in pg_get_functiondef('maintenance.get_customer_procurement(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'currency filter validated');
select ok(position('p_from>p_to' in pg_get_functiondef('maintenance.get_customer_procurement(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'date range validated');
select ok(position('customer_maintenance_scope_matches' in pg_get_functiondef('maintenance.get_customer_procurement(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'work-order scope helper enforced');
select ok(position('scope_property_id' in pg_get_functiondef('maintenance.get_customer_procurement(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'building and unit contexts resolve their property scope');
select ok(position('maintenance.work_order_assignments' in pg_get_functiondef('maintenance.get_customer_procurement(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'narrow vendor visibility requires scoped commercial activity');
select ok(position('contract_ref_encrypted' in pg_get_functiondef('maintenance.get_customer_procurement(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))=0,'encrypted contract reference never projected');
select ok(position('scope_snapshot' in pg_get_functiondef('maintenance.get_customer_procurement(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))=0,'quote scope snapshots never projected');
select ok(position('snapshot_json' in pg_get_functiondef('maintenance.get_customer_procurement(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))=0,'purchase-order snapshots never projected');
select ok(position('approved_by' in pg_get_functiondef('maintenance.get_customer_procurement(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))=0,'approver identity never projected');
select ok(position('vc.rate_card' in pg_get_functiondef('maintenance.get_customer_procurement(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'authorized contract rate card projected');
select ok(position('(vq.subtotal+vq.tax_total)' in pg_get_functiondef('maintenance.get_customer_procurement(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'quote total calculated by database');
select ok(position($n$then 'expired'$n$ in pg_get_functiondef('maintenance.get_customer_procurement(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'expired quote status calculated by database');
select ok(position('(po.ledger_journal_id is not null) ledger_linked' in pg_get_functiondef('maintenance.get_customer_procurement(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure))>0,'ledger relationship exposed only as a boolean');
select ok(position($n$'commercial_data_redacted',true$n$ in regexp_replace(pg_get_functiondef('maintenance.get_customer_procurement(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'\s+','','g'))>0,'commercial projection declares redaction');
select ok(position($n$'read_only',true$n$ in regexp_replace(pg_get_functiondef('maintenance.get_customer_procurement(uuid,text,text,text,text,date,date,integer,integer,uuid)'::regprocedure),'\s+','','g'))>0,'RPC declares read-only');
select ok(not has_function_privilege('anon','maintenance.get_customer_procurement(uuid,text,text,text,text,date,date,integer,integer,uuid)','EXECUTE'),'anon cannot execute procurement RPC');
select ok(has_function_privilege('authenticated','maintenance.get_customer_procurement(uuid,text,text,text,text,date,date,integer,integer,uuid)','EXECUTE'),'authenticated can execute gated procurement RPC');
select ok(not has_table_privilege('authenticated','maintenance.vendors','SELECT'),'raw vendors cannot bypass safe projection');
select ok(not has_table_privilege('authenticated','maintenance.vendor_contracts','SELECT'),'raw contracts cannot bypass safe projection');
select ok(not has_table_privilege('authenticated','maintenance.vendor_quotes','SELECT'),'raw quotes cannot bypass safe projection');
select ok(not has_table_privilege('authenticated','maintenance.purchase_orders','SELECT'),'raw purchase orders cannot bypass safe projection');
select ok(not has_table_privilege('authenticated','maintenance.sla_measurements','SELECT'),'raw SLA measurements cannot bypass safe projection');
select ok(not exists(select 1 from identity.role_permissions rp join identity.permissions p on p.id=rp.permission_id join identity.roles r on r.id=rp.role_id where p.code='maintenance.procurement.read' and rp.effect='allow' and lower(r.code) in ('owner','tenant_resident')),'resident roles do not receive commercial procurement permission');

select * from finish();
rollback;
