'use client';
/* eslint-disable react-hooks/set-state-in-effect -- request state is synchronized with query controls */
import { useCallback, useEffect, useState } from 'react';
import { Plus, RotateCcw, Search, XCircle } from 'lucide-react';

type Task={id:string;run_id:string;task_order:number;task_type:string;status:string;attempt_count:number;started_at:string|null;completed_at:string|null;failure_reason:string|null};
type Run={id:string;customer_workspace_id:string;idempotency_key:string;status:string;initiated_by:string|null;started_at:string;completed_at:string|null;failure_reason:string|null;created_at:string;tasks:Task[]};
type Eligible={workspace_id:string;workspace_type:string;commercial_owner:string;environment:string};
type Payload={runs:Run[];eligibleWorkspaces:Eligible[];canManage:boolean;pagination:{total:number;limit:number;offset:number;hasMore:boolean}};
const copy={en:{search:'Search key or workspace ID',all:'All statuses',new:'Queue run',loading:'Loading live provisioning runs…',empty:'No provisioning runs match these filters.',error:'Provisioning runs could not be loaded.',previous:'Previous',next:'Next',details:'Run details',tasks:'Tasks',workspace:'Workspace',initiator:'Initiator',started:'Started',completed:'Completed',cancel:'Cancel run',retry:'Retry',attempts:'attempts',eligible:'Eligible workspace',key:'Idempotency key',queue:'Queue provisioning',close:'Close'},ro:{search:'Caută cheia sau ID-ul spațiului',all:'Toate stările',new:'Pune în coadă',loading:'Se încarcă execuțiile reale…',empty:'Nicio execuție nu corespunde filtrelor.',error:'Execuțiile nu au putut fi încărcate.',previous:'Anterior',next:'Următor',details:'Detalii execuție',tasks:'Sarcini',workspace:'Spațiu',initiator:'Inițiator',started:'Pornit',completed:'Finalizat',cancel:'Anulează',retry:'Reîncearcă',attempts:'încercări',eligible:'Spațiu eligibil',key:'Cheie de idempotentă',queue:'Pune provisionarea în coadă',close:'Închide'},fa:{search:'جست‌وجوی کلید یا شناسه فضای کاری',all:'همه وضعیت‌ها',new:'ایجاد Run',loading:'در حال بارگذاری اجراهای واقعی…',empty:'اجرایی با این فیلترها یافت نشد.',error:'بارگذاری اجراها ممکن نشد.',previous:'قبلی',next:'بعدی',details:'جزئیات اجرا',tasks:'وظایف',workspace:'فضای کاری',initiator:'آغازکننده',started:'شروع',completed:'پایان',cancel:'لغو اجرا',retry:'تلاش مجدد',attempts:'تلاش',eligible:'فضای کاری واجد شرایط',key:'کلید Idempotency',queue:'قرار دادن در صف',close:'بستن'}} as const;

export function OperationalProvisioningPanel({lang}:{lang:string}) {
  const l=copy[lang==='fa'?'fa':lang==='ro'?'ro':'en'];
  const [data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[offset,setOffset]=useState(0),[status,setStatus]=useState(''),[q,setQ]=useState(''),[query,setQuery]=useState(''),[selected,setSelected]=useState<Run|null>(null),[creating,setCreating]=useState(false);
  const load=useCallback(async()=>{setLoading(true);setError('');try{const p=new URLSearchParams({limit:'12',offset:String(offset)});if(status)p.set('status',status);if(query)p.set('q',query);const r=await fetch(`/api/platform/v1/provisioning?${p}`,{cache:'no-store'});if(!r.ok)throw new Error();setData(await r.json())}catch{setError(l.error)}finally{setLoading(false)}},[offset,status,query,l.error]);
  useEffect(()=>{void load()},[load]);
  return <div className="space-y-4"><form onSubmit={e=>{e.preventDefault();setOffset(0);setQuery(q.trim())}} className="flex flex-wrap gap-3 rounded-xl border border-[#1E3A5A] bg-[#0F2236] p-4"><label className="relative min-w-64 flex-1"><Search className="absolute start-3 top-2.5 h-4 w-4 text-slate-500"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={l.search} className="w-full rounded border border-[#1E3A5A] bg-[#081320] py-2 pe-3 ps-9 text-sm text-white"/></label><select value={status} onChange={e=>{setStatus(e.target.value);setOffset(0)}} className="rounded border border-[#1E3A5A] bg-[#081320] px-3 text-sm text-white"><option value="">{l.all}</option>{['queued','running','completed','failed','cancelled'].map(x=><option key={x}>{x}</option>)}</select><button className="rounded border border-[#1D4A73] px-4 py-2 text-emerald-300">{l.search}</button>{data?.canManage&&<button type="button" onClick={()=>setCreating(true)} disabled={!data.eligibleWorkspaces.length} className="ms-auto flex items-center gap-2 rounded bg-emerald-500 px-4 py-2 font-bold text-[#081320] disabled:opacity-40"><Plus className="h-4 w-4"/>{l.new}</button>}</form>
  {loading?<Box text={l.loading}/>:error?<Box text={error}/>:!data?.runs.length?<Box text={l.empty}/>:<><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.runs.map(run=><article key={run.id} className="rounded-xl border border-[#1E3A5A] bg-[#0F2236] p-5"><div className="flex justify-between"><Status value={run.status}/><span className="text-xs text-slate-400">{run.tasks.length} {l.tasks}</span></div><button onClick={()=>setSelected(run)} className="mt-3 block max-w-full truncate text-start font-mono text-sm font-bold text-white">{run.idempotency_key}</button><p className="mt-2 truncate font-mono text-xs text-emerald-400">{run.customer_workspace_id}</p><div className="mt-4 space-y-1 text-xs text-slate-400"><p>{l.started}: {new Date(run.started_at).toLocaleString(lang)}</p><p>{l.completed}: {run.completed_at?new Date(run.completed_at).toLocaleString(lang):'—'}</p></div>{data.canManage&&['queued','running','failed'].includes(run.status)&&<button onClick={()=>void mutate(`/api/platform/v1/provisioning/${run.id}/cancel`,l.cancel,load)} className="mt-4 flex items-center gap-2 rounded border border-rose-500/40 px-3 py-1 text-xs text-rose-300"><XCircle className="h-4 w-4"/>{l.cancel}</button>}</article>)}</div><Pager offset={offset} data={data} setOffset={setOffset} l={l}/></>}
  {selected&&<Detail run={selected} canManage={Boolean(data?.canManage)} close={()=>setSelected(null)} reload={async()=>{setSelected(null);await load()}} lang={lang} l={l}/>} {creating&&data&&<CreateRun workspaces={data.eligibleWorkspaces} close={()=>setCreating(false)} done={load} lang={lang} l={l}/>}</div>;
}
function Box({text}:{text:string}){return <div className="rounded-xl border border-[#1E3A5A] bg-[#0F2236] p-10 text-center text-sm text-slate-300">{text}</div>}
function Status({value}:{value:string}){const color=value==='failed'||value==='cancelled'?'border-rose-500/40 text-rose-300':value==='completed'?'border-emerald-500/40 text-emerald-300':'border-sky-500/40 text-sky-300';return <span className={`rounded-full border px-2 py-0.5 text-[10px] uppercase ${color}`}>{value}</span>}
function Pager({offset,data,setOffset,l}:{offset:number;data:Payload;setOffset:(n:number)=>void;l:typeof copy.en|typeof copy.ro|typeof copy.fa}){return <div className="flex justify-between text-xs text-slate-400"><span>{offset+1}–{Math.min(offset+12,data.pagination.total)} / {data.pagination.total}</span><div className="flex gap-2"><button disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-12))} className="rounded border border-[#1E3A5A] px-3 py-2 disabled:opacity-40">{l.previous}</button><button disabled={!data.pagination.hasMore} onClick={()=>setOffset(offset+12)} className="rounded border border-[#1E3A5A] px-3 py-2 disabled:opacity-40">{l.next}</button></div></div>}
async function mutate(url:string,promptLabel:string,done:()=>Promise<void>){const reason=window.prompt(`${promptLabel} — audit reason (8–500 characters)`);if(!reason)return;const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reason})});if(r.ok)await done();else window.alert('Provisioning operation failed.');}
function Detail({run,canManage,close,reload,lang,l}:{run:Run;canManage:boolean;close:()=>void;reload:()=>Promise<void>;lang:string;l:typeof copy.en|typeof copy.ro|typeof copy.fa}){return <section className="rounded-xl border border-emerald-500/30 bg-[#0F2236] p-5 text-sm text-slate-300"><div className="flex justify-between"><h2 className="font-bold text-white">{l.details} · {run.idempotency_key}</h2><button onClick={close}>{l.close} ×</button></div><dl className="mt-4 grid gap-2 text-xs md:grid-cols-2"><div><dt className="text-slate-500">{l.workspace}</dt><dd className="font-mono">{run.customer_workspace_id}</dd></div><div><dt className="text-slate-500">{l.initiator}</dt><dd className="font-mono">{run.initiated_by??'—'}</dd></div></dl><h3 className="mt-5 font-bold text-white">{l.tasks}</h3><div className="mt-2 space-y-2">{run.tasks.map(task=><div key={task.id} className="flex flex-wrap items-center gap-3 rounded border border-[#1E3A5A] bg-[#081320] p-3"><span className="w-6 text-slate-500">{task.task_order+1}</span><span className="min-w-48 flex-1 font-mono text-xs">{task.task_type}</span><Status value={task.status}/><span className="text-xs text-slate-500">{task.attempt_count} {l.attempts}</span>{canManage&&task.status==='failed'&&<button onClick={()=>void mutate(`/api/platform/v1/provisioning/tasks/${task.id}/retry`,l.retry,reload)} className="flex items-center gap-1 text-emerald-300"><RotateCcw className="h-3 w-3"/>{l.retry}</button>}{task.failure_reason&&<p className="basis-full text-xs text-rose-300">{task.failure_reason}</p>}</div>)}</div><p className="mt-4 text-xs text-slate-500">{new Date(run.created_at).toLocaleString(lang)}</p></section>}
function CreateRun({workspaces,close,done,lang,l}:{workspaces:Eligible[];close:()=>void;done:()=>Promise<void>;lang:string;l:typeof copy.en|typeof copy.ro|typeof copy.fa}){const[busy,setBusy]=useState(false),[error,setError]=useState('');async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);const r=await fetch('/api/platform/v1/provisioning',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workspace_id:f.get('workspace_id'),idempotency_key:f.get('idempotency_key')})});setBusy(false);if(!r.ok){setError(lang==='fa'?'ایجاد Run انجام نشد؛ شرایط Workspace یا کلید را بررسی کنید.':'Run creation failed; verify eligibility and key.');return}close();await done()}return <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><form onSubmit={submit} className="w-full max-w-xl space-y-4 rounded-xl border border-[#1E3A5A] bg-[#0F2236] p-6 text-sm text-white"><h2 className="font-bold">{l.queue}</h2><label className="block">{l.eligible}<select required name="workspace_id" className="mt-1 w-full rounded bg-[#081320] p-3">{workspaces.map(w=><option key={w.workspace_id} value={w.workspace_id}>{w.commercial_owner} · {w.workspace_type} · {w.environment}</option>)}</select></label><label className="block">{l.key}<input required minLength={8} maxLength={128} pattern="[A-Za-z0-9][A-Za-z0-9._:-]{7,127}" name="idempotency_key" className="mt-1 w-full rounded bg-[#081320] p-3 font-mono" placeholder="workspace:phase:request-id"/></label>{error&&<p className="text-rose-300">{error}</p>}<div className="flex justify-end gap-2"><button type="button" onClick={close} className="rounded border border-[#1E3A5A] px-4 py-2">{l.close}</button><button disabled={busy} className="rounded bg-emerald-500 px-4 py-2 font-bold text-[#081320] disabled:opacity-50">{l.queue}</button></div></form></div>}
