'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { Check, ChevronLeft, ChevronRight, Eye, Plus, Search, ShieldX, X } from 'lucide-react';

type Item = { request_id:string; workspace_id:string; workspace_label:string; ticket_ref:string; purpose:string; requested_scope:string; sensitivity_level:string; requester_name:string; request_status:string; requested_duration_minutes:number; request_evidence:Record<string,unknown>; requested_at:string; grant_id:string|null; approver_name:string|null; starts_at:string|null; expires_at:string|null; revoked_at:string|null; revoke_reason:string|null; activation_evidence:Record<string,unknown>|null; effective_status:string };
type Workspace = { workspace_id:string; workspace_label:string };
type ResponseData = { items:Item[]; workspaces:Workspace[]; canManage:boolean; pagination:{total:number;limit:number;offset:number;hasMore:boolean} };

const copy = {
  ro:{search:'Caută tichet, motiv sau spațiu',status:'Toate stările',workspace:'Toate spațiile',apply:'Aplică',clear:'Șterge',new:'Cerere nouă',loading:'Se încarcă accesul protejat…',empty:'Nu există cereri în domeniul autorizat.',error:'Datele de suport nu au putut fi încărcate.',ticket:'Tichet',target:'Spațiu / scop',state:'Stare',time:'Durată / expirare',actions:'Acțiuni',details:'Detalii',approve:'Aprobă independent',cancel:'Anulează cererea',revoke:'Revocă accesul',reason:'Motiv obligatoriu (8–500)',evidence:'Referință evidence obligatorie',purpose:'Justificare (8–500)',duration:'Durată (minute)',create:'Creează cererea',close:'Închide',total:'cereri autorizate'},
  en:{search:'Search ticket, reason, or workspace',status:'All states',workspace:'All workspaces',apply:'Apply',clear:'Clear',new:'New request',loading:'Loading protected support access…',empty:'No requests in your authorized scope.',error:'Support access data could not be loaded.',ticket:'Ticket',target:'Workspace / scope',state:'State',time:'Duration / expiry',actions:'Actions',details:'Details',approve:'Independent approval',cancel:'Cancel request',revoke:'Revoke access',reason:'Required reason (8–500)',evidence:'Required evidence reference',purpose:'Reason (8–500)',duration:'Duration (minutes)',create:'Create request',close:'Close',total:'authorized requests'},
  fa:{search:'جست‌وجوی تیکت، دلیل یا محیط کاری',status:'همه وضعیت‌ها',workspace:'همه محیط‌ها',apply:'اعمال',clear:'پاک‌کردن',new:'درخواست جدید',loading:'در حال بارگذاری دسترسی محافظت‌شده…',empty:'در دامنه مجاز شما درخواستی وجود ندارد.',error:'بارگذاری داده پشتیبانی ممکن نشد.',ticket:'تیکت',target:'محیط / دامنه',state:'وضعیت',time:'مدت / انقضا',actions:'عملیات',details:'جزئیات',approve:'تأیید مستقل',cancel:'لغو درخواست',revoke:'لغو دسترسی',reason:'دلیل الزامی (۸ تا ۵۰۰)',evidence:'مرجع مدرک الزامی',purpose:'توجیه (۸ تا ۵۰۰)',duration:'مدت (دقیقه)',create:'ایجاد درخواست',close:'بستن',total:'درخواست مجاز'},
} as const;
const statuses=['','requested','approved','cancelled','revoked','expired'];

export function OperationalSupportPanel({lang}:{lang:string}) {
  const locale=lang==='ro'||lang==='fa'?lang:'en'; const l=copy[locale];
  const [data,setData]=useState<ResponseData|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [offset,setOffset]=useState(0);
  const [draft,setDraft]=useState({q:'',status:'',workspace_id:''}); const [filters,setFilters]=useState(draft); const [selected,setSelected]=useState<Item|null>(null); const [createOpen,setCreateOpen]=useState(false); const [busy,setBusy]=useState(false);
  const [form,setForm]=useState({workspace_id:'',ticket_ref:'',purpose:'',requested_scope:'technical',sensitivity_level:'standard',duration_minutes:60,evidence:''});
  const load=useCallback(async()=>{await Promise.resolve();setLoading(true);setError('');try{const p=new URLSearchParams({limit:'20',offset:String(offset)});Object.entries(filters).forEach(([k,v])=>{if(v)p.set(k,v)});const r=await fetch(`/api/platform/v1/support?${p}`,{cache:'no-store',credentials:'same-origin'});if(!r.ok)throw new Error();setData(await r.json())}catch{setError(l.error)}finally{setLoading(false)}},[filters,offset,l.error]);
  useEffect(()=>{const controller=new AbortController();const timer=window.setTimeout(()=>{if(!controller.signal.aborted)void load()},0);return()=>{controller.abort();window.clearTimeout(timer)}},[load]);
  const range=useMemo(()=>!data?.pagination.total?'0':`${data.pagination.offset+1}–${Math.min(data.pagination.offset+data.items.length,data.pagination.total)} / ${data.pagination.total}`,[data]);
  async function mutate(url:string,body:Record<string,unknown>){setBusy(true);setError('');try{const r=await fetch(url,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const payload=await r.json();if(!r.ok)throw new Error(payload?.error?.code||'mutation');setSelected(null);setCreateOpen(false);await load()}catch(e){setError(e instanceof Error?e.message:l.error)}finally{setBusy(false)}}
  function action(item:Item,kind:'approve'|'cancel'|'revoke'){const value=window.prompt(kind==='approve'?l.evidence:l.reason);if(!value)return;const url=kind==='revoke'?`/api/platform/v1/support/grants/${item.grant_id}/revoke`:`/api/platform/v1/support/requests/${item.request_id}/${kind}`;void mutate(url,kind==='approve'?{evidence:value}:{reason:value})}
  return <div className="space-y-4">
    {error?<div role="alert" className="rounded-lg border border-rose-500/40 bg-rose-950/50 p-3 text-xs text-rose-200">{error}</div>:null}
    <div className="rounded-xl border border-[#1E3A5A] bg-[#0F2236] p-4"><div className="grid gap-3 md:grid-cols-3">
      <label className="relative"><Search className="absolute start-3 top-3 h-4 w-4 text-slate-500"/><input aria-label={l.search} value={draft.q} onChange={e=>setDraft({...draft,q:e.target.value})} placeholder={l.search} className="w-full rounded-lg border border-[#29445F] bg-[#081320] py-2.5 ps-9 pe-3 text-xs text-white"/></label>
      <select aria-label={l.status} value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})} className="rounded-lg border border-[#29445F] bg-[#081320] px-3 py-2.5 text-xs text-white">{statuses.map(s=><option key={s} value={s}>{s||l.status}</option>)}</select>
      <select aria-label={l.workspace} value={draft.workspace_id} onChange={e=>setDraft({...draft,workspace_id:e.target.value})} className="rounded-lg border border-[#29445F] bg-[#081320] px-3 py-2.5 text-xs text-white"><option value="">{l.workspace}</option>{data?.workspaces.map(w=><option key={w.workspace_id} value={w.workspace_id}>{w.workspace_label}</option>)}</select>
    </div><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>{setOffset(0);setFilters(draft)}} className="rounded-lg bg-emerald-500 px-4 py-2 text-xs font-bold text-[#081320]">{l.apply}</button><button onClick={()=>{const e={q:'',status:'',workspace_id:''};setDraft(e);setFilters(e);setOffset(0)}} className="rounded-lg border border-[#29445F] px-4 py-2 text-xs text-white">{l.clear}</button>{data?.canManage?<button onClick={()=>setCreateOpen(true)} className="ms-auto inline-flex items-center gap-1 rounded-lg bg-teal-500 px-4 py-2 text-xs font-bold text-[#081320]"><Plus className="h-4 w-4"/>{l.new}</button>:null}<span className="self-center text-xs text-slate-400">{range} {l.total}</span></div></div>
    <div className="overflow-hidden rounded-xl border border-[#1E3A5A] bg-[#0F2236]">{loading?<div className="p-10 text-center text-sm text-slate-400">{l.loading}</div>:!data?.items.length?<div className="p-10 text-center text-sm text-slate-400">{l.empty}</div>:<div className="overflow-x-auto"><table className="w-full min-w-[900px] text-xs"><thead className="bg-[#081320] text-start text-[10px] uppercase text-slate-400"><tr><th className="p-3">{l.ticket}</th><th className="p-3">{l.target}</th><th className="p-3">{l.state}</th><th className="p-3">{l.time}</th><th className="p-3">{l.actions}</th></tr></thead><tbody className="divide-y divide-[#1E3A5A]">{data.items.map(i=><tr key={i.request_id} className="text-slate-300"><td className="p-3"><b className="text-white">{i.ticket_ref}</b><div className="max-w-64 truncate text-slate-500">{i.purpose}</div></td><td className="p-3">{i.workspace_label}<div className="text-slate-500">{i.requested_scope} · {i.sensitivity_level}</div></td><td className="p-3"><span className="rounded-full border border-teal-500/30 px-2 py-1 text-teal-300">{i.effective_status}</span></td><td className="p-3">{i.requested_duration_minutes} min<div className="text-slate-500">{i.expires_at?new Date(i.expires_at).toLocaleString(locale):'—'}</div></td><td className="p-3"><div className="flex gap-1"><button aria-label={l.details} onClick={()=>setSelected(i)} className="rounded border border-[#29445F] p-2"><Eye className="h-4 w-4"/></button>{data.canManage&&i.effective_status==='requested'?<><button aria-label={l.approve} disabled={busy} onClick={()=>action(i,'approve')} className="rounded border border-emerald-500/40 p-2 text-emerald-300"><Check className="h-4 w-4"/></button><button aria-label={l.cancel} disabled={busy} onClick={()=>action(i,'cancel')} className="rounded border border-amber-500/40 p-2 text-amber-300"><X className="h-4 w-4"/></button></>:null}{data.canManage&&i.effective_status==='approved'&&i.grant_id?<button aria-label={l.revoke} disabled={busy} onClick={()=>action(i,'revoke')} className="rounded border border-rose-500/40 p-2 text-rose-300"><ShieldX className="h-4 w-4"/></button>:null}</div></td></tr>)}</tbody></table></div>}<div className="flex justify-end gap-2 border-t border-[#1E3A5A] p-3"><button aria-label="Previous page" disabled={!data||offset===0} onClick={()=>setOffset(Math.max(0,offset-20))} className="rounded border border-[#29445F] p-2 disabled:opacity-30"><ChevronLeft className="h-4 w-4 rtl:rotate-180"/></button><button aria-label="Next page" disabled={!data?.pagination.hasMore} onClick={()=>setOffset(offset+20)} className="rounded border border-[#29445F] p-2 disabled:opacity-30"><ChevronRight className="h-4 w-4 rtl:rotate-180"/></button></div></div>
    {createOpen?<div role="dialog" aria-modal="true" className="fixed inset-0 z-[70] flex items-center justify-center bg-black/70 p-4"><form onSubmit={e=>{e.preventDefault();void mutate('/api/platform/v1/support',{...form,duration_minutes:Number(form.duration_minutes)})}} className="w-full max-w-xl space-y-3 rounded-xl border border-[#29445F] bg-[#0F2236] p-5"><h2 className="font-bold text-white">{l.new}</h2><select required value={form.workspace_id} onChange={e=>setForm({...form,workspace_id:e.target.value})} className="w-full rounded bg-[#081320] p-3 text-xs text-white"><option value="">{l.workspace}</option>{data?.workspaces.map(w=><option key={w.workspace_id} value={w.workspace_id}>{w.workspace_label}</option>)}</select><input required minLength={3} maxLength={100} value={form.ticket_ref} onChange={e=>setForm({...form,ticket_ref:e.target.value})} placeholder={l.ticket} className="w-full rounded bg-[#081320] p-3 text-xs text-white"/><textarea required minLength={8} maxLength={500} value={form.purpose} onChange={e=>setForm({...form,purpose:e.target.value})} placeholder={l.purpose} className="w-full rounded bg-[#081320] p-3 text-xs text-white"/><div className="grid grid-cols-2 gap-3"><select value={form.requested_scope} onChange={e=>setForm({...form,requested_scope:e.target.value})} className="rounded bg-[#081320] p-3 text-xs text-white"><option>diagnostic</option><option>technical</option><option>data_review</option></select><select value={form.sensitivity_level} onChange={e=>setForm({...form,sensitivity_level:e.target.value})} className="rounded bg-[#081320] p-3 text-xs text-white"><option>standard</option><option>sensitive</option><option>critical</option></select></div><input type="number" min={15} max={240} value={form.duration_minutes} onChange={e=>setForm({...form,duration_minutes:Number(e.target.value)})} aria-label={l.duration} className="w-full rounded bg-[#081320] p-3 text-xs text-white"/><input required minLength={3} maxLength={1000} value={form.evidence} onChange={e=>setForm({...form,evidence:e.target.value})} placeholder={l.evidence} className="w-full rounded bg-[#081320] p-3 text-xs text-white"/><div className="flex gap-2"><button disabled={busy} className="rounded bg-emerald-500 px-4 py-2 text-xs font-bold text-[#081320]">{l.create}</button><button type="button" onClick={()=>setCreateOpen(false)} className="rounded border border-[#29445F] px-4 py-2 text-xs text-white">{l.close}</button></div></form></div>:null}
    {selected?<div role="dialog" aria-modal="true" className="fixed inset-0 z-[70] flex items-center justify-center bg-black/70 p-4" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><div className="max-h-[90vh] w-full max-w-3xl overflow-auto rounded-xl border border-[#29445F] bg-[#0F2236] p-5 text-xs text-slate-300"><button onClick={()=>setSelected(null)} className="float-end"><X/></button><h2 className="mb-4 text-base font-bold text-white">{selected.ticket_ref}</h2><dl className="grid gap-3 md:grid-cols-2"><div><dt className="text-slate-500">{l.target}</dt><dd>{selected.workspace_label} · {selected.requested_scope}</dd></div><div><dt className="text-slate-500">{l.state}</dt><dd>{selected.effective_status}</dd></div><div><dt>Requester</dt><dd>{selected.requester_name}</dd></div><div><dt>Approver</dt><dd>{selected.approver_name||'—'}</dd></div><div className="md:col-span-2"><dt>{l.purpose}</dt><dd>{selected.purpose}</dd></div><div><dt>Request evidence</dt><dd><pre className="break-all whitespace-pre-wrap">{JSON.stringify(selected.request_evidence,null,2)}</pre></dd></div><div><dt>Approval evidence</dt><dd><pre className="break-all whitespace-pre-wrap">{JSON.stringify(selected.activation_evidence,null,2)}</pre></dd></div></dl></div></div>:null}
  </div>;
}
