'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {ChevronLeft,ChevronRight,ExternalLink,RefreshCw,Search,ShieldAlert,X} from 'lucide-react';
import type {Language} from '@/types';
import {useCustomerContext} from './CustomerContextProvider';
type Invoice={id:string;invoice_no:number;period_start:string;period_end:string;issued_on:string|null;due_on:string|null;currency:string;subtotal:number;tax_total:number;total:number;status:string;original_amount:number;paid_amount:number;credited_amount:number;outstanding_amount:number;overdue:boolean;journal_id:string|null;journal_no:number|null};
type Line={id:string;description:string;quantity:number;unit_price:number;tax_rate:number;line_subtotal:number;line_tax:number};
type Summary={currency:string;invoice_total:number;paid_total:number;outstanding_total:number;invoice_count:number;overdue_count:number};type Aging={currency:string;current:number;days_1_30:number;days_31_60:number;days_61_90:number;days_90_plus:number};
type Billing={total:number;invoices:Invoice[];summary:Summary[];aging:Aging[];lines:Line[];journal:null|{id:string;journal_no:number;status:string;occurred_on:string;entries:{id:string;account_code:string;side:string;amount:number}[]};limit:number;offset:number;read_only:boolean};
const copy={ro:{title:'Facturi și creanțe',sub:'Date financiare limitate la contextul activ',search:'Caută număr sau descriere',all:'Toate stările',empty:'Nu există facturi pentru filtrele selectate.',error:'Datele de facturare nu au putut fi încărcate.',loading:'Se încarcă datele financiare securizate…',invoiced:'Facturat',paid:'Plătit',outstanding:'Restant',overdue:'Scadent',aging:'Vechimea creanțelor',current:'Curent',days:'zile',invoice:'Factură',period:'Perioadă',due:'Scadență',status:'Stare',total:'Total',balance:'Sold',detail:'Detalii factură',lines:'Linii factură',journal:'Înregistrare contabilă',readonly:'Numai citire'},en:{title:'Billing, invoices and receivables',sub:'Financial records limited to the active context',search:'Search number or description',all:'All statuses',empty:'No invoices match the selected filters.',error:'Billing data could not be loaded.',loading:'Loading secured financial records…',invoiced:'Invoiced',paid:'Paid',outstanding:'Outstanding',overdue:'Overdue',aging:'Receivables aging',current:'Current',days:'days',invoice:'Invoice',period:'Period',due:'Due',status:'Status',total:'Total',balance:'Balance',detail:'Invoice detail',lines:'Invoice lines',journal:'Ledger posting',readonly:'Read-only'},fa:{title:'صورتحساب‌ها و مطالبات',sub:'داده‌های مالی محدود به زمینه فعال',search:'جست‌وجوی شماره یا شرح',all:'همه وضعیت‌ها',empty:'صورتحسابی مطابق فیلترها وجود ندارد.',error:'بارگذاری اطلاعات صورتحساب ناموفق بود.',loading:'در حال بارگذاری امن اطلاعات مالی…',invoiced:'صورتحساب‌شده',paid:'پرداخت‌شده',outstanding:'مانده',overdue:'سررسیدگذشته',aging:'عمر مطالبات',current:'جاری',days:'روز',invoice:'صورتحساب',period:'دوره',due:'سررسید',status:'وضعیت',total:'جمع',balance:'مانده',detail:'جزئیات صورتحساب',lines:'اقلام صورتحساب',journal:'ثبت دفتر کل',readonly:'فقط خواندنی'}};
const statusText={ro:{issued:'Emisă',partially_paid:'Plătită parțial',paid:'Plătită',overdue:'Scadentă',void:'Anulată',credited:'Creditată'},en:{issued:'Issued',partially_paid:'Partially paid',paid:'Paid',overdue:'Overdue',void:'Void',credited:'Credited'},fa:{issued:'صادرشده',partially_paid:'پرداخت جزئی',paid:'پرداخت‌شده',overdue:'سررسیدگذشته',void:'باطل‌شده',credited:'بستانکارشده'}};
const money=(n:number,c:string,l:Language)=>new Intl.NumberFormat(l==='fa'?'fa-IR':l==='ro'?'ro-RO':'en-US',{style:'currency',currency:c,maximumFractionDigits:2}).format(n);
export function CustomerBillingDashboard({lang}:{lang:Language}){const{active}=useCustomerContext(),t=copy[lang];const[data,setData]=useState<Billing|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(false),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[offset,setOffset]=useState(0),[selected,setSelected]=useState<Invoice|null>(null),[nonce,setNonce]=useState(0);const limit=25;
const load=useCallback(async(invoiceId?:string)=>{if(!active)return;setLoading(true);setError(false);try{const p=new URLSearchParams({context_id:active.context_id,limit:String(limit),offset:String(offset)});if(query.trim())p.set('query',query.trim());if(status)p.set('status',status);if(from)p.set('from',from);if(to)p.set('to',to);if(invoiceId)p.set('invoice_id',invoiceId);const response=await fetch('/api/customer/v1/billing?'+p,{cache:'no-store',credentials:'same-origin'});if(!response.ok)throw new Error('billing');setData(await response.json() as Billing)}catch{setError(true)}finally{setLoading(false)}},[active,from,offset,query,status,to]);
useEffect(()=>{const timer=setTimeout(()=>void load(),250);return()=>clearTimeout(timer)},[load,nonce]);const pages=useMemo(()=>Math.max(1,Math.ceil((data?.total??0)/limit)),[data?.total]),page=Math.floor(offset/limit)+1;
async function open(invoice:Invoice){setSelected(invoice);await load(invoice.id)}function close(){setSelected(null);void load()}
if(!active)return <div className="rounded-2xl bg-white p-8">{t.empty}</div>;if(loading&&!data)return <div className="rounded-2xl bg-white p-8">{t.loading}</div>;
return <section className="space-y-5" dir={lang==='fa'?'rtl':'ltr'}><header className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h1 className="text-2xl font-bold">{t.title}</h1><span className="rounded-full bg-[#EAF8F5] px-2 py-1 text-[10px] font-bold text-[#0A6E62]">{t.readonly}</span></div><p className="mt-1 text-sm text-[#52667A]">{t.sub}</p></div><button type="button" onClick={()=>setNonce(n=>n+1)} disabled={loading} aria-label="Refresh" className="rounded-xl border bg-white p-2"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button></header>
{data?.summary.map(s=><div key={s.currency} className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[t.invoiced,s.invoice_total],[t.paid,s.paid_total],[t.outstanding,s.outstanding_total],[t.overdue,s.overdue_count]].map(([label,value],i)=><article key={label} className="rounded-2xl border bg-white p-4"><div className="text-xs text-[#52667A]">{label} · {s.currency}</div><div className="mt-2 text-xl font-bold">{i===3?value:money(Number(value),s.currency,lang)}</div></article>)}</div>)}
{data?.aging.map(a=><article key={a.currency} className="rounded-2xl border bg-white p-4"><h2 className="text-xs font-bold text-[#52667A]">{t.aging} · {a.currency}</h2><div className="mt-3 grid gap-2 sm:grid-cols-5">{[[t.current,a.current],[`1–30 ${t.days}`,a.days_1_30],[`31–60 ${t.days}`,a.days_31_60],[`61–90 ${t.days}`,a.days_61_90],[`90+ ${t.days}`,a.days_90_plus]].map(([label,value])=><div key={label} className="rounded-xl bg-[#F6F9FC] p-3 text-xs"><div>{label}</div><strong>{money(Number(value),a.currency,lang)}</strong></div>)}</div></article>)}
<div className="flex flex-col gap-3 rounded-2xl border bg-white p-4 lg:flex-row"><label className="relative flex-1"><Search className="absolute start-3 top-2.5 h-4 w-4 text-[#7B8A9A]"/><span className="sr-only">{t.search}</span><input value={query} onChange={e=>{setQuery(e.target.value);setOffset(0)}} placeholder={t.search} className="w-full rounded-xl border py-2 pe-3 ps-9 text-sm"/></label><select aria-label={t.status} value={status} onChange={e=>{setStatus(e.target.value);setOffset(0)}} className="rounded-xl border px-3 py-2 text-sm"><option value="">{t.all}</option>{['issued','partially_paid','paid','overdue','void','credited'].map(x=><option key={x} value={x}>{statusText[lang][x as keyof typeof statusText.en]}</option>)}</select><input type="date" aria-label={`${t.invoice} ${t.period}`} value={from} onChange={e=>{setFrom(e.target.value);setOffset(0)}} className="rounded-xl border px-3 py-2 text-sm"/><input type="date" aria-label={t.due} value={to} onChange={e=>{setTo(e.target.value);setOffset(0)}} className="rounded-xl border px-3 py-2 text-sm"/></div>
{error?<div role="alert" className="flex gap-2 rounded-2xl border border-red-200 bg-red-50 p-5 text-red-800"><ShieldAlert className="h-5 w-5"/>{t.error}</div>:<div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full text-sm"><thead className="bg-[#F6F9FC] text-xs text-[#52667A]"><tr><th className="p-3 text-start">{t.invoice}</th><th className="p-3 text-start">{t.period}</th><th className="p-3 text-start">{t.due}</th><th className="p-3 text-start">{t.status}</th><th className="p-3 text-end">{t.total}</th><th className="p-3 text-end">{t.balance}</th></tr></thead><tbody>{data?.invoices.map(i=><tr key={i.id} className="border-t"><td className="p-3"><button type="button" onClick={()=>void open(i)} className="rounded font-mono underline decoration-dotted focus:ring-2 focus:ring-[#0E9F8E]">#{i.invoice_no}</button></td><td className="p-3">{i.period_start} — {i.period_end}</td><td className="p-3">{i.due_on??'—'}</td><td className="p-3"><span className={`rounded-full px-2 py-1 text-xs ${i.overdue?'bg-red-50 text-red-700':'bg-slate-100'}`}>{statusText[lang][(i.overdue?'overdue':i.status) as keyof typeof statusText.en]??i.status}</span></td><td className="p-3 text-end">{money(i.total,i.currency,lang)}</td><td className="p-3 text-end font-bold">{money(i.outstanding_amount,i.currency,lang)}</td></tr>)}</tbody></table>{!loading&&data?.invoices.length===0?<div className="p-8 text-center text-sm text-[#52667A]">{t.empty}</div>:null}</div>}
<div className="flex items-center justify-end gap-3"><button type="button" disabled={page<=1} onClick={()=>setOffset(Math.max(0,offset-limit))} className="rounded-xl border bg-white p-2" aria-label="Previous"><ChevronLeft className="h-4 w-4"/></button><span className="text-xs">{page} / {pages}</span><button type="button" disabled={page>=pages} onClick={()=>setOffset(offset+limit)} className="rounded-xl border bg-white p-2" aria-label="Next"><ChevronRight className="h-4 w-4"/></button></div>
{selected?<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div role="dialog" aria-modal="true" aria-label={t.detail} className="max-h-[85vh] w-full max-w-2xl overflow-auto rounded-2xl bg-white p-6"><div className="flex justify-between"><h2 className="font-bold">{t.detail} #{selected.invoice_no}</h2><button type="button" onClick={close} aria-label="Close"><X/></button></div><h3 className="mt-5 text-xs font-bold text-[#52667A]">{t.lines}</h3><div className="mt-2 space-y-2">{data?.lines.map(l=><div key={l.id} className="grid grid-cols-[1fr_auto] gap-3 rounded-xl bg-[#F6F9FC] p-3 text-sm"><span>{l.description}<small className="block text-[#52667A]">{l.quantity} × {money(l.unit_price,selected.currency,lang)}</small></span><strong>{money(l.line_subtotal+l.line_tax,selected.currency,lang)}</strong></div>)}</div>{data?.journal?<div className="mt-5 rounded-xl border p-3 text-sm"><div className="flex items-center gap-2 font-bold"><ExternalLink className="h-4 w-4"/>{t.journal} #{data.journal.journal_no}</div><div className="mt-2 space-y-1">{data.journal.entries.map(e=><div key={e.id} className="flex justify-between text-xs"><span>{e.account_code} · {e.side}</span><strong>{money(e.amount,selected.currency,lang)}</strong></div>)}</div></div>:null}</div></div>:null}</section>}
