"use client";
import { useCallback, useEffect, useState } from "react";
import { Building2, ChevronLeft, ChevronRight, RefreshCw, Search, ShieldCheck, UsersRound, X } from "lucide-react";
import type { Language } from "@/types";
import { useCustomerContext } from "./CustomerContextProvider";

export type OccupancyView = "parties" | "residents" | "ownerships" | "leases" | "occupancies" | "mappings" | "links" | "history";
type Row = Record<string, unknown> & { id?: string };
type Response = { rows: Row[]; total: number; summary?: Record<string, number>; detail?: Row | null; read_only: boolean; pii_redacted: boolean };
const copy = {
 en:{title:"Occupancy, ownership & lease registry",sub:"Authorized parties, residents, ownership shares and lease periods with privacy-safe identities.",search:"Search authorized registry",status:"Status",all:"All occupancy types",refresh:"Refresh",loading:"Loading authorized registry…",empty:"No registry records are visible in this context.",error:"The occupancy registry could not be loaded.",readonly:"Read-only · personal data redacted",details:"Details",close:"Close",parties:"Parties",residents:"Residents",ownerships:"Ownership",leases:"Leases",occupancies:"Occupancy",mappings:"Party mappings",links:"Related records",history:"Lifecycle",units:"Visible units",occupied:"Occupied",vacant:"Vacant",active_leases:"Active leases",previous:"Previous",next:"Next"},
 ro:{title:"Registru de ocupare, proprietate și închiriere",sub:"Părți autorizate, rezidenți, cote de proprietate și perioade de închiriere cu identități protejate.",search:"Caută în registrul autorizat",status:"Stare",all:"Toate tipurile de ocupare",refresh:"Reîncarcă",loading:"Se încarcă registrul autorizat…",empty:"Nu există înregistrări vizibile în acest context.",error:"Registrul de ocupare nu a putut fi încărcat.",readonly:"Doar citire · date personale redactate",details:"Detalii",close:"Închide",parties:"Părți",residents:"Rezidenți",ownerships:"Proprietate",leases:"Contracte",occupancies:"Ocupare",mappings:"Asocieri părți",links:"Înregistrări asociate",history:"Ciclu de viață",units:"Unități vizibile",occupied:"Ocupate",vacant:"Libere",active_leases:"Contracte active",previous:"Anterior",next:"Următor"},
 fa:{title:"دفتر سکونت، مالکیت و اجاره",sub:"اشخاص مجاز، ساکنان، سهم مالکیت و دوره‌های اجاره با حفاظت از هویت و اطلاعات شخصی.",search:"جستجو در دفتر مجاز",status:"وضعیت",all:"همه انواع سکونت",refresh:"بازخوانی",loading:"در حال دریافت دفتر مجاز…",empty:"در این زمینه رکوردی قابل مشاهده نیست.",error:"دریافت دفتر سکونت ناموفق بود.",readonly:"فقط خواندنی · اطلاعات شخصی پوشانده شده",details:"جزئیات",close:"بستن",parties:"اشخاص",residents:"ساکنان",ownerships:"مالکیت",leases:"اجاره‌ها",occupancies:"سکونت",mappings:"نگاشت اشخاص",links:"سوابق مرتبط",history:"چرخه عمر",units:"واحدهای قابل مشاهده",occupied:"اشغال‌شده",vacant:"خالی",active_leases:"اجاره فعال",previous:"قبلی",next:"بعدی"},
} as const;
const views:OccupancyView[]=["occupancies","residents","ownerships","leases","parties","mappings","links","history"];
const hidden=new Set(["id","entity_id","party_id","membership_id"]);
function display(v:unknown){if(v===null||v===undefined||v==="")return"—";if(typeof v==="boolean")return v?"✓":"—";if(typeof v==="object")return JSON.stringify(v);return String(v).replace("T"," ").replace(/\.\d{3}Z$/," UTC");}
export function CustomerOccupancyDashboard({lang,initialView="occupancies",initialId}:{lang:Language;initialView?:OccupancyView;initialId?:string}){
 const{active}=useCustomerContext(),t=copy[lang];
 const[view,setView]=useState<OccupancyView>(initialView),[query,setQuery]=useState(""),[status,setStatus]=useState(""),[kind,setKind]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[offset,setOffset]=useState(0),[data,setData]=useState<Response|null>(null),[selected,setSelected]=useState<Row|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=useCallback(async()=>{if(!active){setLoading(false);setData(null);return;}setLoading(true);setError("");try{const p=new URLSearchParams({context_id:active.context_id,view,limit:"20",offset:String(offset)});if(query)p.set("query",query);if(status)p.set("status",status);if(kind)p.set("kind",kind);if(from)p.set("from",from);if(to)p.set("to",to);if(initialId&&view===initialView)p.set("id",initialId);const response=await fetch(`/api/customer/v1/occupancy?${p}`,{ cache: "no-store", credentials: "same-origin" });if(!response.ok)throw new Error();const body=await response.json()as Response;setData(body);if(initialId&&body.rows[0])setSelected(body.rows[0]);}catch{setError(t.error);}finally{setLoading(false);}},[active,view,offset,query,status,kind,from,to,initialId,initialView,t.error]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),150);return()=>clearTimeout(timer);},[load]);
 const summary=data?.summary??{};
 return <div className="space-y-5" dir={lang==="fa"?"rtl":"ltr"}>
  <header className="card-proptech border border-[#D3DCE6] bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-[#0E9F8E]"><ShieldCheck className="h-4 w-4"/>CLADORA · Occupancy registry</div><h1 className="mt-1 text-2xl font-extrabold text-[#102A43]">{t.title}</h1><p className="mt-1 max-w-3xl text-xs text-[#52667A]">{t.sub}</p></div><span className="rounded-full border border-[#B2E5DF] bg-[#EAF8F5] px-3 py-1 text-[11px] font-bold text-[#0A6E62]">{t.readonly}</span></div></header>
  <section className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[[t.units,summary.units??0],[t.occupied,summary.occupied??0],[t.vacant,summary.vacant??0],[t.active_leases,summary.active_leases??0]].map(([label,value])=><div key={String(label)} className="card-proptech bg-white p-4"><div className="text-[11px] text-[#52667A]">{label}</div><div className="mt-1 text-xl font-extrabold">{value}</div></div>)}</section>
  <section className="card-proptech overflow-hidden bg-white"><div className="flex gap-1 overflow-x-auto border-b p-2">{views.map(item=><button type="button" key={item} onClick={()=>{setView(item);setOffset(0);setSelected(null);}} className={`whitespace-nowrap rounded-lg px-3 py-2 text-xs font-bold ${view===item?"bg-[#0E9F8E] text-white":"text-[#52667A] hover:bg-[#F6F9FC]"}`}>{t[item]}</button>)}</div>
   <div className="grid gap-2 border-b p-3 md:grid-cols-6"><label className="relative md:col-span-2"><Search className="absolute start-3 top-2.5 h-4 w-4 text-[#7B8A9A]"/><input value={query} onChange={e=>{setQuery(e.target.value);setOffset(0);}} placeholder={t.search} className="w-full rounded-lg border py-2 pe-3 ps-9 text-xs"/></label><input value={status} onChange={e=>{setStatus(e.target.value);setOffset(0);}} placeholder={t.status} className="rounded-lg border px-3 py-2 text-xs"/><select value={kind} onChange={e=>{setKind(e.target.value);setOffset(0);}} className="rounded-lg border px-3 py-2 text-xs"><option value="">{t.all}</option>{["owner","tenant","household_member","short_stay","company","empty"].map(x=><option value={x} key={x}>{x.replaceAll("_"," ")}</option>)}</select><input aria-label="From" type="date" value={from} onChange={e=>setFrom(e.target.value)} className="rounded-lg border px-2 py-2 text-xs"/><div className="flex gap-2"><input aria-label="To" type="date" value={to} onChange={e=>setTo(e.target.value)} className="min-w-0 flex-1 rounded-lg border px-2 py-2 text-xs"/><button type="button" onClick={()=>void load()} aria-label={t.refresh} className="rounded-lg border p-2"><RefreshCw className={`h-4 w-4 ${loading?"animate-spin":""}`}/></button></div></div>
   {loading?<div className="p-10 text-center text-xs text-[#52667A]">{t.loading}</div>:error?<div role="alert" className="p-10 text-center text-xs font-bold text-red-700">{error}</div>:!data?.rows.length?<div className="p-10 text-center text-xs text-[#52667A]"><UsersRound className="mx-auto mb-2 h-7 w-7"/>{t.empty}</div>:<div className="divide-y">{data.rows.map((row,index)=>{const entries=Object.entries(row).filter(([key])=>!hidden.has(key)).slice(0,7);return <article key={row.id??`${view}-${index}`} className="flex items-center gap-3 p-4"><div className="rounded-xl bg-[#EAF8F5] p-2 text-[#0E9F8E]"><Building2 className="h-5 w-5"/></div><div className="min-w-0 flex-1"><div className="truncate text-xs font-bold">{display(row.unit_code??row.display_name??row.resident_label??row.party_label??row.event_type??`#${index+1}`)}</div><div className="mt-1 flex flex-wrap gap-x-3 gap-y-1 text-[10px] text-[#64748B]">{entries.slice(1).map(([key,value])=><span key={key}><b>{key.replaceAll("_"," ")}:</b> {display(value)}</span>)}</div></div><button type="button" onClick={()=>setSelected(row)} className="rounded-lg border px-3 py-2 text-[11px] font-bold">{t.details}</button></article>;})}</div>}
   <div className="flex items-center justify-between border-t p-3 text-xs"><button type="button" disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-20))} className="flex items-center gap-1 rounded-lg border px-3 py-2 disabled:opacity-40"><ChevronLeft className="h-4 w-4"/>{t.previous}</button><span>{offset+1}–{Math.min(offset+20,data?.total??0)} / {data?.total??0}</span><button type="button" disabled={offset+20>=(data?.total??0)} onClick={()=>setOffset(offset+20)} className="flex items-center gap-1 rounded-lg border px-3 py-2 disabled:opacity-40">{t.next}<ChevronRight className="h-4 w-4"/></button></div>
  </section>
  {selected?<div className="fixed inset-0 z-50 flex items-end justify-end bg-[#102A43]/35 p-4" role="dialog" aria-modal="true"><div className="max-h-[85vh] w-full max-w-xl overflow-auto rounded-2xl bg-white p-5 shadow-xl"><div className="flex items-center justify-between"><h2 className="font-bold">{t.details}</h2><button type="button" onClick={()=>setSelected(null)} aria-label={t.close}><X className="h-5 w-5"/></button></div><dl className="mt-4 grid gap-3 sm:grid-cols-2">{Object.entries(selected).filter(([key])=>!hidden.has(key)).map(([key,value])=><div key={key} className="rounded-xl bg-[#F6F9FC] p-3"><dt className="text-[10px] font-bold uppercase text-[#64748B]">{key.replaceAll("_"," ")}</dt><dd className="mt-1 break-words text-xs">{display(value)}</dd></div>)}</dl></div></div>:null}
 </div>;
}
