'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {ChevronLeft,ChevronRight,RefreshCw,Search,ShieldAlert,X} from 'lucide-react';
import type {Language} from '@/types';
import {useCustomerContext} from './CustomerContextProvider';
type Journal={id:string;journal_no:number;occurred_on:string;currency:string;description:string;source_type:string;status:string;posted_at:string|null;debit_total:number;credit_total:number;balanced:boolean};
type Account={id:string;code:string;name:string;type:string;currency:string;balance:number};
type Period={id:string;starts_on:string;ends_on:string;status:'open'|'closed';closed_at:string|null};
type Entry={id:string;account_code:string;account_name:string;side:string;amount:number;memo:string|null};
type Ledger={context:{tenant_name:string;role_code:string;scope_type:string};total:number;journals:Journal[];accounts:Account[];periods:Period[];trial_balance:{debit:number;credit:number;balanced:boolean};detail:Entry[];limit:number;offset:number;read_only:boolean};
const text={ro:{title:'Registru contabil',sub:'Jurnale și balanță limitate la contextul activ',search:'Caută descriere, număr sau sursă',all:'Toate stările',allAccounts:'Toate tipurile de cont',empty:'Nu există înregistrări pentru filtrele selectate.',error:'Registrul nu a putut fi încărcat.',accounts:'Plan de conturi',periods:'Perioade contabile',journals:'Jurnale',trial:'Balanță de verificare',debit:'Debit',credit:'Credit',balanced:'Echilibrat',unbalanced:'Dezechilibrat',date:'Data',description:'Descriere',status:'Stare',amount:'Total',detail:'Detalii jurnal',readonly:'Numai citire',open:'Deschisă',closed:'Închisă'},en:{title:'Accounting ledger',sub:'Journals and trial balance limited to the active context',search:'Search description, number or source',all:'All statuses',allAccounts:'All account types',empty:'No records match the selected filters.',error:'The ledger could not be loaded.',accounts:'Chart of accounts',periods:'Accounting periods',journals:'Journals',trial:'Trial balance',debit:'Debit',credit:'Credit',balanced:'Balanced',unbalanced:'Unbalanced',date:'Date',description:'Description',status:'Status',amount:'Total',detail:'Journal detail',readonly:'Read-only',open:'Open',closed:'Closed'},fa:{title:'دفتر کل حسابداری',sub:'اسناد و تراز محدود به زمینه فعال',search:'جست‌وجوی شرح، شماره یا منبع',all:'همه وضعیت‌ها',allAccounts:'همه انواع حساب',empty:'رکوردی مطابق فیلترها وجود ندارد.',error:'بارگذاری دفتر کل ناموفق بود.',accounts:'کدینگ حساب‌ها',periods:'دوره‌های حسابداری',journals:'اسناد روزنامه',trial:'تراز آزمایشی',debit:'بدهکار',credit:'بستانکار',balanced:'تراز',unbalanced:'نامتوازن',date:'تاریخ',description:'شرح',status:'وضعیت',amount:'جمع',detail:'جزئیات سند',readonly:'فقط خواندنی',open:'باز',closed:'بسته'}};
const money=(value:number,currency:string,lang:Language)=>new Intl.NumberFormat(lang==='fa'?'fa-IR':lang==='ro'?'ro-RO':'en-US',{style:'currency',currency,maximumFractionDigits:2}).format(value);
export function CustomerAccountingLedger({lang}:{lang:Language}){const{active}=useCustomerContext(),t=text[lang];const[data,setData]=useState<Ledger|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(false),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[accountType,setAccountType]=useState(''),[offset,setOffset]=useState(0),[selected,setSelected]=useState<Journal|null>(null),[nonce,setNonce]=useState(0);const limit=25;
const load=useCallback(async(journalId?:string)=>{if(!active)return;setLoading(true);setError(false);try{const params=new URLSearchParams({context_id:active.context_id,limit:String(limit),offset:String(offset)});if(query.trim())params.set('query',query.trim());if(status)params.set('status',status);if(accountType)params.set('account_type',accountType);if(journalId)params.set('journal_id',journalId);const response=await fetch('/api/customer/v1/accounting?'+params,{cache:'no-store'});if(!response.ok)throw new Error('ledger');const body=await response.json() as Ledger;setData(body)}catch{setError(true)}finally{setLoading(false)}},[accountType,active,offset,query,status]);
useEffect(()=>{const timer=setTimeout(()=>void load(),250);return()=>clearTimeout(timer)},[load,nonce]);
const pages=useMemo(()=>Math.max(1,Math.ceil((data?.total??0)/limit)),[data?.total]);const page=Math.floor(offset/limit)+1;
async function open(journal:Journal){setSelected(journal);await load(journal.id)}
function close(){setSelected(null);void load()}
if(!active)return <div className="rounded-2xl bg-white p-8">{t.empty}</div>;
return <section className="space-y-5" dir={lang==='fa'?'rtl':'ltr'}><header className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h1 className="text-2xl font-bold">{t.title}</h1><span className="rounded-full bg-[#EAF8F5] px-2 py-1 text-[10px] font-bold text-[#0A6E62]">{t.readonly}</span></div><p className="mt-1 text-sm text-[#52667A]">{t.sub}</p></div><button type="button" onClick={()=>setNonce(n=>n+1)} disabled={loading} className="rounded-xl border bg-white p-2" aria-label="Refresh"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button></header>
<div className="grid gap-4 md:grid-cols-3"><article className="rounded-2xl border bg-white p-5 md:col-span-2"><div className="text-xs text-[#52667A]">{t.trial}</div><div className="mt-3 flex flex-wrap gap-8"><div><div className="text-xs">{t.debit}</div><strong>{money(data?.trial_balance.debit??0,'RON',lang)}</strong></div><div><div className="text-xs">{t.credit}</div><strong>{money(data?.trial_balance.credit??0,'RON',lang)}</strong></div><span className={`self-end rounded-full px-3 py-1 text-xs font-bold ${data?.trial_balance.balanced?'bg-emerald-50 text-emerald-700':'bg-red-50 text-red-700'}`}>{data?.trial_balance.balanced?t.balanced:t.unbalanced}</span></div></article><article className="rounded-2xl border bg-white p-5"><div className="text-xs text-[#52667A]">{t.periods}</div><div className="mt-2 space-y-2">{data?.periods.map(period=><div key={period.id} className="text-xs"><span className="font-mono">{period.starts_on} — {period.ends_on}</span> · <strong>{period.status==='closed'?t.closed:t.open}</strong></div>)}{data?.periods.length===0?<div className="text-sm text-[#52667A]">{t.empty}</div>:null}</div></article></div>
<div className="rounded-2xl border bg-white p-4"><div className="mb-3 text-xs font-bold text-[#52667A]">{t.accounts}</div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{data?.accounts.map(account=><div key={account.id} className="rounded-xl bg-[#F6F9FC] p-3 text-xs"><strong className="font-mono">{account.code}</strong> · {account.name}<div className="mt-1 text-[#52667A]">{account.type} · {money(account.balance,account.currency,lang)}</div></div>)}</div></div>
<div className="flex flex-col gap-3 rounded-2xl border bg-white p-4 sm:flex-row"><label className="relative flex-1"><Search className="absolute start-3 top-2.5 h-4 w-4 text-[#7B8A9A]"/><span className="sr-only">{t.search}</span><input value={query} onChange={e=>{setQuery(e.target.value);setOffset(0)}} placeholder={t.search} className="w-full rounded-xl border py-2 pe-3 ps-9 text-sm"/></label><select aria-label={t.status} value={status} onChange={e=>{setStatus(e.target.value);setOffset(0)}} className="rounded-xl border px-3 py-2 text-sm"><option value="">{t.all}</option><option value="posted">Posted</option><option value="draft">Draft</option><option value="reversed">Reversed</option></select><select aria-label={t.accounts} value={accountType} onChange={e=>setAccountType(e.target.value)} className="rounded-xl border px-3 py-2 text-sm"><option value="">{t.allAccounts}</option>{['asset','liability','equity','income','expense'].map(type=><option key={type} value={type}>{type}</option>)}</select></div>
{error?<div role="alert" className="flex gap-2 rounded-2xl border border-red-200 bg-red-50 p-5 text-red-800"><ShieldAlert className="h-5 w-5"/>{t.error}</div>:<div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full text-sm"><thead className="bg-[#F6F9FC] text-xs text-[#52667A]"><tr><th className="p-3 text-start">#</th><th className="p-3 text-start">{t.date}</th><th className="p-3 text-start">{t.description}</th><th className="p-3 text-start">{t.status}</th><th className="p-3 text-end">{t.amount}</th></tr></thead><tbody>{data?.journals.map(j=><tr key={j.id} className="border-t hover:bg-[#F6F9FC]"><td className="p-3 font-mono"><button type="button" onClick={()=>void open(j)} className="rounded underline decoration-dotted underline-offset-2 focus:outline-none focus:ring-2 focus:ring-[#0E9F8E]">{j.journal_no}</button></td><td className="p-3">{j.occurred_on}</td><td className="p-3"><div className="font-medium">{j.description}</div><div className="text-[10px] text-[#7B8A9A]">{j.source_type}</div></td><td className="p-3"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs">{j.status}</span></td><td className="p-3 text-end font-bold">{money(j.debit_total,j.currency,lang)}</td></tr>)}</tbody></table>{!loading&&data?.journals.length===0?<div className="p-8 text-center text-sm text-[#52667A]">{t.empty}</div>:null}</div>}
<div className="flex items-center justify-end gap-3"><button type="button" disabled={page<=1} onClick={()=>setOffset(Math.max(0,offset-limit))} className="rounded-xl border bg-white p-2"><ChevronLeft className="h-4 w-4"/></button><span className="text-xs">{page} / {pages}</span><button type="button" disabled={page>=pages} onClick={()=>setOffset(offset+limit)} className="rounded-xl border bg-white p-2"><ChevronRight className="h-4 w-4"/></button></div>
{selected?<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div role="dialog" aria-modal="true" aria-label={t.detail} className="max-h-[85vh] w-full max-w-2xl overflow-auto rounded-2xl bg-white p-6"><div className="flex justify-between"><div><h2 className="font-bold">{t.detail} #{selected.journal_no}</h2><p className="text-xs text-[#52667A]">{selected.description}</p></div><button type="button" onClick={close} aria-label="Close"><X/></button></div><div className="mt-5 space-y-2">{data?.detail.map(e=><div key={e.id} className="grid grid-cols-[1fr_auto] gap-3 rounded-xl bg-[#F6F9FC] p-3 text-sm"><div><strong className="font-mono">{e.account_code}</strong> · {e.account_name}<div className="text-xs text-[#52667A]">{e.memo}</div></div><div className={e.side==='debit'?'text-[#0A6E62]':'text-[#173F5F]'}>{e.side==='debit'?t.debit:t.credit}<br/><strong>{money(e.amount,selected.currency,lang)}</strong></div></div>)}</div></div></div>:null}</section>}
