'use client';
import {useCallback,useEffect,useState} from 'react';
import {ChevronLeft,ChevronRight,ExternalLink,RefreshCw,Search,ShieldAlert,X} from 'lucide-react';
import type {Language} from '@/types';
import {useCustomerContext} from './CustomerContextProvider';
type View='payments'|'reconciliation';
type Payment={id:string;provider_ref:string|null;amount:number;currency:string;paid_at:string;status:string;allocated_amount:number;unallocated_amount:number;journal_no:number|null};
type Match={id:string;booked_on:string;direction:string;transaction_amount:number;currency:string;matched_amount:number;confidence:number|null;status:string;provider_ref:string|null;invoice_no:number|null};
type Summary={currency:string;paid:number;reconciled:number;unallocated:number;unmatched_count:number};
type Journal={journal_no:number;status:string;occurred_on:string;entries:{id:string;account_code:string;side:string;amount:number}[]};
type Payload={view:View;total:number;payments:Payment[];reconciliations:Match[];summary:Summary[];journal:Journal|null;limit:number;offset:number;read_only:boolean};
const copy={ro:{title:'Plăți și reconciliere bancară',sub:'Proiecție securizată, exclusiv pentru citire',payments:'Plăți',reconciliation:'Reconciliere',search:'Caută referință, factură sau jurnal',all:'Toate stările',date:'Data',reference:'Referință',status:'Stare',amount:'Sumă',allocated:'Alocat',unallocated:'Nealocat',reconciled:'Reconciliat',unmatched:'Fără asociere',invoice:'Factură',confidence:'Încredere',journal:'Jurnal contabil',empty:'Nu există înregistrări pentru filtrele selectate.',error:'Datele nu au putut fi încărcate în siguranță.',loading:'Se încarcă datele financiare…',readonly:'Numai citire'},en:{title:'Payments & bank reconciliation',sub:'Secure, read-only financial projection',payments:'Payments',reconciliation:'Reconciliation',search:'Search reference, invoice or journal',all:'All statuses',date:'Date',reference:'Reference',status:'Status',amount:'Amount',allocated:'Allocated',unallocated:'Unallocated',reconciled:'Reconciled',unmatched:'Unmatched',invoice:'Invoice',confidence:'Confidence',journal:'Accounting journal',empty:'No records match the selected filters.',error:'Financial data could not be loaded safely.',loading:'Loading financial data…',readonly:'Read only'},fa:{title:'پرداخت‌ها و تطبیق بانکی',sub:'نمای مالی امن و فقط خواندنی',payments:'پرداخت‌ها',reconciliation:'تطبیق بانکی',search:'جست‌وجوی مرجع، صورتحساب یا دفتر',all:'همه وضعیت‌ها',date:'تاریخ',reference:'مرجع',status:'وضعیت',amount:'مبلغ',allocated:'تخصیص‌یافته',unallocated:'تخصیص‌نیافته',reconciled:'تطبیق‌شده',unmatched:'بدون تطبیق',invoice:'صورتحساب',confidence:'اطمینان',journal:'دفتر حسابداری',empty:'رکوردی مطابق فیلترهای انتخاب‌شده وجود ندارد.',error:'داده مالی به‌صورت امن بارگذاری نشد.',loading:'در حال بارگذاری داده مالی…',readonly:'فقط خواندنی'}};
const statuses={payments:['pending','settled','failed','refunded'],reconciliation:['unmatched','suggested','confirmed','rejected']};
const money=(n:number,c:string,l:Language)=>new Intl.NumberFormat(l==='fa'?'fa-IR':l==='ro'?'ro-RO':'en-US',{style:'currency',currency:c,maximumFractionDigits:2}).format(n);
export function CustomerPaymentsDashboard({lang,initialView}:{lang:Language;initialView:View}){const{active}=useCustomerContext(),t=copy[lang];const[data,setData]=useState<Payload|null>(null),[view,setView]=useState<View>(initialView),[loading,setLoading]=useState(false),[error,setError]=useState(false),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[offset,setOffset]=useState(0),[selected,setSelected]=useState<Payment|null>(null),[nonce,setNonce]=useState(0);const limit=25;
const load=useCallback(async(id?:string)=>{if(!active)return;setLoading(true);setError(false);try{const p=new URLSearchParams({context_id:active.context_id,view,limit:String(limit),offset:String(offset)});if(query.trim())p.set('query',query.trim());if(status)p.set('status',status);if(from)p.set('from',from);if(to)p.set('to',to);if(id)p.set('id',id);const response=await fetch('/api/customer/v1/payments?'+p,{cache:'no-store',credentials:'same-origin'});if(!response.ok)throw new Error('payments');setData(await response.json() as Payload)}catch{setError(true)}finally{setLoading(false)}},[active,from,offset,query,status,to,view]);
useEffect(()=>{const timer=setTimeout(()=>void load(),250);return()=>clearTimeout(timer)},[load,nonce]);const pages=Math.max(1,Math.ceil((data?.total??0)/limit)),page=Math.floor(offset/limit)+1;
function changeView(next:View){setView(next);setStatus('');setOffset(0);setSelected(null);setData(null)}async function open(payment:Payment){setSelected(payment);await load(payment.id)}function close(){setSelected(null);void load()}
if(!active)return <div className="rounded-2xl bg-white p-8">{t.empty}</div>;if(loading&&!data)return <div className="rounded-2xl bg-white p-8">{t.loading}</div>;
return <section className="space-y-5" dir={lang==='fa'?'rtl':'ltr'}><header className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h1 className="text-2xl font-bold">{t.title}</h1><span className="rounded-full bg-[#EAF8F5] px-2 py-1 text-[10px] font-bold text-[#0A6E62]">{t.readonly}</span></div><p className="mt-1 text-sm text-[#52667A]">{t.sub}</p></div><button type="button" onClick={()=>setNonce(n=>n+1)} disabled={loading} aria-label="Refresh" className="rounded-xl border bg-white p-2"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button></header>
<div className="inline-flex rounded-xl border bg-white p-1"><button type="button" onClick={()=>changeView('payments')} aria-pressed={view==='payments'} className={`rounded-lg px-4 py-2 text-xs font-bold ${view==='payments'?'bg-[#0E9F8E] text-white':''}`}>{t.payments}</button><button type="button" onClick={()=>changeView('reconciliation')} aria-pressed={view==='reconciliation'} className={`rounded-lg px-4 py-2 text-xs font-bold ${view==='reconciliation'?'bg-[#0E9F8E] text-white':''}`}>{t.reconciliation}</button></div>
{data?.summary.map(s=><div key={s.currency} className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[t.amount,s.paid],[t.reconciled,s.reconciled],[t.unallocated,s.unallocated],[t.unmatched,s.unmatched_count]].map(([label,value],i)=><article key={label} className="rounded-2xl border bg-white p-4"><div className="text-xs text-[#52667A]">{label} · {s.currency}</div><div className="mt-2 text-xl font-bold">{i===3?value:money(Number(value),s.currency,lang)}</div></article>)}</div>)}
<div className="flex flex-col gap-3 rounded-2xl border bg-white p-4 lg:flex-row"><label className="relative flex-1"><Search className="absolute start-3 top-2.5 h-4 w-4 text-[#7B8A9A]"/><span className="sr-only">{t.search}</span><input value={query} onChange={e=>{setQuery(e.target.value);setOffset(0)}} placeholder={t.search} className="w-full rounded-xl border py-2 pe-3 ps-9 text-sm"/></label><select aria-label={t.status} value={status} onChange={e=>{setStatus(e.target.value);setOffset(0)}} className="rounded-xl border px-3 py-2 text-sm"><option value="">{t.all}</option>{statuses[view].map(x=><option key={x} value={x}>{x.replaceAll('_',' ')}</option>)}</select><input type="date" aria-label={`${t.date} from`} value={from} onChange={e=>{setFrom(e.target.value);setOffset(0)}} className="rounded-xl border px-3 py-2 text-sm"/><input type="date" aria-label={`${t.date} to`} value={to} onChange={e=>{setTo(e.target.value);setOffset(0)}} className="rounded-xl border px-3 py-2 text-sm"/></div>
{error?<div role="alert" className="flex gap-2 rounded-2xl border border-red-200 bg-red-50 p-5 text-red-800"><ShieldAlert className="h-5 w-5"/>{t.error}</div>:<div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full text-sm"><thead className="bg-[#F6F9FC] text-xs text-[#52667A]"><tr><th className="p-3 text-start">{t.date}</th><th className="p-3 text-start">{t.reference}</th><th className="p-3 text-start">{view==='payments'?t.allocated:t.invoice}</th><th className="p-3 text-start">{t.status}</th><th className="p-3 text-end">{t.amount}</th></tr></thead><tbody>{view==='payments'?data?.payments.map(p=><tr key={p.id} className="border-t"><td className="p-3">{p.paid_at.slice(0,10)}</td><td className="p-3"><button type="button" onClick={()=>void open(p)} className="rounded font-mono underline decoration-dotted focus:ring-2 focus:ring-[#0E9F8E]">{p.provider_ref??p.id.slice(0,8)}</button></td><td className="p-3">{money(p.allocated_amount,p.currency,lang)}</td><td className="p-3">{p.status}</td><td className="p-3 text-end font-bold">{money(p.amount,p.currency,lang)}</td></tr>):data?.reconciliations.map(m=><tr key={m.id} className="border-t"><td className="p-3">{m.booked_on}</td><td className="p-3 font-mono">{m.provider_ref??'—'}</td><td className="p-3">{m.invoice_no?`#${m.invoice_no}`:'—'}</td><td className="p-3">{m.status}{m.confidence!==null?` · ${Math.round(m.confidence*100)}%`:''}</td><td className="p-3 text-end font-bold">{money(m.matched_amount,m.currency,lang)}</td></tr>)}</tbody></table>{!loading&&((view==='payments'?data?.payments.length:data?.reconciliations.length)??0)===0?<div className="p-8 text-center text-sm text-[#52667A]">{t.empty}</div>:null}</div>}
<div className="flex items-center justify-end gap-3"><button type="button" disabled={page<=1} onClick={()=>setOffset(Math.max(0,offset-limit))} className="rounded-xl border bg-white p-2" aria-label="Previous"><ChevronLeft className="h-4 w-4"/></button><span className="text-xs">{page} / {pages}</span><button type="button" disabled={page>=pages} onClick={()=>setOffset(offset+limit)} className="rounded-xl border bg-white p-2" aria-label="Next"><ChevronRight className="h-4 w-4"/></button></div>
{selected?<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div role="dialog" aria-modal="true" aria-label={t.journal} className="max-h-[85vh] w-full max-w-2xl overflow-auto rounded-2xl bg-white p-6"><div className="flex justify-between"><h2 className="font-bold">{t.reference}: {selected.provider_ref??selected.id}</h2><button type="button" onClick={close} aria-label="Close"><X/></button></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><div>{t.amount}<strong className="block">{money(selected.amount,selected.currency,lang)}</strong></div><div>{t.allocated}<strong className="block">{money(selected.allocated_amount,selected.currency,lang)}</strong></div><div>{t.unallocated}<strong className="block">{money(selected.unallocated_amount,selected.currency,lang)}</strong></div></div>{data?.journal?<div className="mt-5 rounded-xl border p-3 text-sm"><div className="flex items-center gap-2 font-bold"><ExternalLink className="h-4 w-4"/>{t.journal} #{data.journal.journal_no}</div><div className="mt-2 space-y-1">{data.journal.entries.map(e=><div key={e.id} className="flex justify-between text-xs"><span>{e.account_code} · {e.side}</span><strong>{money(e.amount,selected.currency,lang)}</strong></div>)}</div></div>:null}</div></div>:null}</section>}
