"use client";

import { useCallback, useEffect, useState } from "react";
import { Archive, ChevronLeft, ChevronRight, FileCheck2, FileText, RefreshCw, Search, ShieldCheck, X } from "lucide-react";
import type { Language } from "@/types";
import { useCustomerContext } from "./CustomerContextProvider";

type View = "documents" | "versions" | "categories" | "retention" | "holds" | "evidence" | "links" | "history";
type Row = Record<string, unknown> & { id?: string };
type Response = { rows: Row[]; total: number; summary?: Record<string, number>; detail?: Row | null; read_only: boolean; storage_access: boolean; signed_urls: boolean };
const copy = {
  en: { title: "Document vault & secure evidence", sub: "Authorized records, immutable versions, retention and evidence metadata—without file paths or downloads.", search: "Search authorized documents", all: "All classifications", status: "Status", from: "From", to: "To", refresh: "Refresh", loading: "Loading authorized document metadata…", empty: "No document records are visible in this context.", error: "Document metadata could not be loaded.", readonly: "Read-only · storage access disabled", details: "Details", close: "Close", documents: "Documents", versions: "Versions", categories: "Categories", retention: "Retention", holds: "Legal holds", evidence: "Evidence", links: "Links", history: "Lifecycle", total: "Visible records", published: "Published", legal: "Legal hold", expiring: "Expiring", previous: "Previous", next: "Next" },
  ro: { title: "Seif de documente și dovezi securizate", sub: "Înregistrări autorizate, versiuni imuabile, retenție și metadate de dovadă—fără căi de fișiere sau descărcări.", search: "Caută documente autorizate", all: "Toate clasificările", status: "Stare", from: "De la", to: "Până la", refresh: "Reîncarcă", loading: "Se încarcă metadatele autorizate…", empty: "Nu există documente vizibile în acest context.", error: "Metadatele documentelor nu au putut fi încărcate.", readonly: "Doar citire · accesul la stocare este dezactivat", details: "Detalii", close: "Închide", documents: "Documente", versions: "Versiuni", categories: "Categorii", retention: "Retenție", holds: "Blocări juridice", evidence: "Dovezi", links: "Legături", history: "Ciclu de viață", total: "Înregistrări vizibile", published: "Publicate", legal: "Blocare juridică", expiring: "Expiră", previous: "Anterior", next: "Următor" },
  fa: { title: "مخزن اسناد و شواهد امن", sub: "سوابق مجاز، نسخه‌های تغییرناپذیر، نگهداری و فراداده شواهد؛ بدون مسیر فایل یا دانلود.", search: "جستجوی اسناد مجاز", all: "همه طبقه‌بندی‌ها", status: "وضعیت", from: "از", to: "تا", refresh: "بازخوانی", loading: "در حال دریافت فراداده مجاز اسناد…", empty: "در این زمینه سندی قابل مشاهده نیست.", error: "دریافت فراداده اسناد ناموفق بود.", readonly: "فقط خواندنی · دسترسی Storage غیرفعال", details: "جزئیات", close: "بستن", documents: "اسناد", versions: "نسخه‌ها", categories: "دسته‌بندی‌ها", retention: "نگهداری", holds: "توقف حقوقی", evidence: "شواهد", links: "ارتباط‌ها", history: "چرخه عمر", total: "سوابق قابل مشاهده", published: "منتشرشده", legal: "توقف حقوقی", expiring: "در آستانه انقضا", previous: "قبلی", next: "بعدی" },
} as const;
const views: View[] = ["documents", "versions", "categories", "retention", "holds", "evidence", "links", "history"];
const hidden = new Set(["id", "document_id", "entity_id"]);
function display(value: unknown) {
  if (value === null || value === undefined || value === "") return "—";
  if (typeof value === "boolean") return value ? "✓" : "—";
  if (typeof value === "object") return JSON.stringify(value);
  return String(value).replace("T", " ").replace(/\.\d{3}Z$/, " UTC");
}
export function CustomerDocumentsDashboard({ lang, initialDocumentId }: { lang: Language; initialDocumentId?: string }) {
  const { active } = useCustomerContext(); const t = copy[lang];
  const [view, setView] = useState<View>("documents"), [query, setQuery] = useState(""), [status, setStatus] = useState(""), [classification, setClassification] = useState(""), [from, setFrom] = useState(""), [to, setTo] = useState(""), [offset, setOffset] = useState(0), [data, setData] = useState<Response | null>(null), [selected, setSelected] = useState<Row | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const load = useCallback(async () => {
    if (!active) { setLoading(false); setData(null); return; }
    setLoading(true); setError("");
    try {
      const p = new URLSearchParams({ context_id: active.context_id, view, limit: "20", offset: String(offset) });
      if (query) p.set("query", query); if (status) p.set("status", status); if (classification) p.set("classification", classification); if (from) p.set("from", from); if (to) p.set("to", to); if (initialDocumentId && view === "documents") p.set("id", initialDocumentId);
      const response = await fetch(`/api/customer/v1/documents?${p}`, { cache: "no-store", credentials: "same-origin" });
      if (!response.ok) throw new Error(); const body = await response.json() as Response; setData(body); if (initialDocumentId && body.rows[0]) setSelected(body.rows[0]);
    } catch { setError(t.error); } finally { setLoading(false); }
  }, [active, view, offset, query, status, classification, from, to, initialDocumentId, t.error]);
  useEffect(() => { const timer = setTimeout(() => void load(), 150); return () => clearTimeout(timer); }, [load]);
  const setActiveView = (next: View) => { setView(next); setOffset(0); setSelected(null); };
  const summary = data?.summary ?? {};
  return <div className="space-y-5" dir={lang === "fa" ? "rtl" : "ltr"}>
    <header className="card-proptech border border-[#D3DCE6] bg-white p-6">
      <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-[#0E9F8E]"><ShieldCheck className="h-4 w-4" />CLADORA · Secure records</div><h1 className="mt-1 text-2xl font-extrabold text-[#102A43]">{t.title}</h1><p className="mt-1 max-w-3xl text-xs text-[#52667A]">{t.sub}</p></div><span className="rounded-full border border-[#B2E5DF] bg-[#EAF8F5] px-3 py-1 text-[11px] font-bold text-[#0A6E62]">{t.readonly}</span></div>
    </header>
    <section className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[[t.total, data?.total ?? 0], [t.published, summary.published ?? 0], [t.legal, summary.legal_hold ?? 0], [t.expiring, summary.expiring ?? 0]].map(([label, value]) => <div key={String(label)} className="card-proptech bg-white p-4"><div className="text-[11px] text-[#52667A]">{label}</div><div className="mt-1 text-xl font-extrabold text-[#102A43]">{value}</div></div>)}</section>
    <section className="card-proptech overflow-hidden bg-white">
      <div className="flex gap-1 overflow-x-auto border-b border-[#E2E8F0] p-2">{views.map((item) => <button type="button" key={item} onClick={() => setActiveView(item)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-xs font-bold ${view === item ? "bg-[#0E9F8E] text-white" : "text-[#52667A] hover:bg-[#F6F9FC]"}`}>{t[item]}</button>)}</div>
      <div className="grid gap-2 border-b border-[#E2E8F0] p-3 md:grid-cols-6"><label className="relative md:col-span-2"><Search className="absolute start-3 top-2.5 h-4 w-4 text-[#7B8A9A]" /><input value={query} onChange={(e) => { setQuery(e.target.value); setOffset(0); }} placeholder={t.search} className="w-full rounded-lg border border-[#CBD5E1] py-2 pe-3 ps-9 text-xs" /></label><input value={status} onChange={(e) => { setStatus(e.target.value); setOffset(0); }} placeholder={t.status} className="rounded-lg border border-[#CBD5E1] px-3 py-2 text-xs" /><select value={classification} onChange={(e) => { setClassification(e.target.value); setOffset(0); }} className="rounded-lg border border-[#CBD5E1] px-3 py-2 text-xs"><option value="">{t.all}</option><option value="public">Public</option><option value="internal">Internal</option><option value="confidential">Confidential</option><option value="restricted">Restricted</option></select><input aria-label={t.from} type="date" value={from} onChange={(e) => setFrom(e.target.value)} className="rounded-lg border border-[#CBD5E1] px-2 py-2 text-xs" /><div className="flex gap-2"><input aria-label={t.to} type="date" value={to} onChange={(e) => setTo(e.target.value)} className="min-w-0 flex-1 rounded-lg border border-[#CBD5E1] px-2 py-2 text-xs" /><button type="button" onClick={() => void load()} aria-label={t.refresh} className="rounded-lg border border-[#CBD5E1] p-2"><RefreshCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`} /></button></div></div>
      {loading ? <div className="p-10 text-center text-xs text-[#52667A]">{t.loading}</div> : error ? <div role="alert" className="p-10 text-center text-xs font-bold text-red-700">{error}</div> : !data?.rows.length ? <div className="p-10 text-center text-xs text-[#52667A]"><Archive className="mx-auto mb-2 h-7 w-7" />{t.empty}</div> : <div className="divide-y divide-[#EDF2F7]">{data.rows.map((row, index) => { const entries = Object.entries(row).filter(([key]) => !hidden.has(key)).slice(0, 6); return <article key={row.id ?? `${view}-${index}`} className="flex items-center gap-3 p-4"><div className="rounded-xl bg-[#EAF8F5] p-2 text-[#0E9F8E]">{view === "evidence" ? <FileCheck2 className="h-5 w-5" /> : <FileText className="h-5 w-5" />}</div><div className="min-w-0 flex-1"><div className="truncate text-xs font-bold text-[#102A43]">{display(row.title ?? row.document_title ?? row.category ?? row.event_type ?? row.entity_type ?? `#${index + 1}`)}</div><div className="mt-1 flex flex-wrap gap-x-3 gap-y-1 text-[10px] text-[#64748B]">{entries.slice(1).map(([key, value]) => <span key={key}><b>{key.replaceAll("_", " ")}:</b> {display(value)}</span>)}</div></div><button type="button" onClick={() => setSelected(row)} className="rounded-lg border border-[#CBD5E1] px-3 py-2 text-[11px] font-bold">{t.details}</button></article>; })}</div>}
      <div className="flex items-center justify-between border-t border-[#E2E8F0] p-3 text-xs"><button type="button" disabled={offset === 0} onClick={() => setOffset(Math.max(0, offset - 20))} className="flex items-center gap-1 rounded-lg border px-3 py-2 disabled:opacity-40"><ChevronLeft className="h-4 w-4" />{t.previous}</button><span>{offset + 1}–{Math.min(offset + 20, data?.total ?? 0)} / {data?.total ?? 0}</span><button type="button" disabled={offset + 20 >= (data?.total ?? 0)} onClick={() => setOffset(offset + 20)} className="flex items-center gap-1 rounded-lg border px-3 py-2 disabled:opacity-40">{t.next}<ChevronRight className="h-4 w-4" /></button></div>
    </section>
    {selected ? <div className="fixed inset-0 z-50 flex items-end justify-end bg-[#102A43]/35 p-4" role="dialog" aria-modal="true"><div className="max-h-[85vh] w-full max-w-xl overflow-auto rounded-2xl bg-white p-5 shadow-xl"><div className="flex items-center justify-between"><h2 className="font-bold text-[#102A43]">{t.details}</h2><button type="button" onClick={() => setSelected(null)} aria-label={t.close}><X className="h-5 w-5" /></button></div><dl className="mt-4 grid gap-3 sm:grid-cols-2">{Object.entries(selected).filter(([key]) => !hidden.has(key)).map(([key, value]) => <div key={key} className="rounded-xl bg-[#F6F9FC] p-3"><dt className="text-[10px] font-bold uppercase text-[#64748B]">{key.replaceAll("_", " ")}</dt><dd className="mt-1 break-words text-xs text-[#102A43]">{display(value)}</dd></div>)}</dl></div></div> : null}
  </div>;
}
