'use client';
import {useCallback,useEffect,useState} from 'react';
import {ChevronLeft,ChevronRight,RefreshCw,Search,Scale,ShieldCheck,X} from 'lucide-react';
import {useCustomerContext} from './CustomerContextProvider';

type View='runs'|'rules'|'lines';
type Summary={currency:string;source_amount:number;allocated_amount:number;difference:number;run_count:number};
type Payload={context:{tenant_name:string;role_code:string;scope_type:string};view:View;total:number;rows:Record<string,unknown>[];summary:Summary[];detail:Record<string,unknown>|null;limit:number;offset:number;read_only:boolean};
const copy={
 en:{title:'Charge Allocation & Financial Rights',sub:'Explainable, versioned allocation evidence with owner–tenant responsibility separation.',runs:'Runs',rules:'Rules',lines:'Allocation lines',search:'Search category, source or run',all:'All',method:'Method',status:'Status',from:'From',to:'To',loading:'Loading authorized allocations…',empty:'No allocations are visible in this context.',error:'Allocation data could not be loaded.',refresh:'Refresh',source:'Source',allocated:'Allocated',difference:'Difference',period:'Period',category:'Category',basis:'Basis',share:'Share',amount:'Amount',debtor:'Legal debtor',payer:'Operational payer',version:'Version',formula:'Formula',evidence:'Evidence',reason:'Reason',details:'Details',close:'Close',readonly:'Read-only financial evidence'},
 ro:{title:'Alocări de costuri și drepturi financiare',sub:'Dovezi explicabile și versionate cu separarea responsabilității proprietar–chiriaș.',runs:'Rulări',rules:'Reguli',lines:'Linii de alocare',search:'Caută categorie, sursă sau rulare',all:'Toate',method:'Metodă',status:'Stare',from:'De la',to:'Până la',loading:'Se încarcă alocările autorizate…',empty:'Nu există alocări vizibile în acest context.',error:'Datele de alocare nu au putut fi încărcate.',refresh:'Reîncarcă',source:'Sursă',allocated:'Alocat',difference:'Diferență',period:'Perioadă',category:'Categorie',basis:'Bază',share:'Cotă',amount:'Sumă',debtor:'Debitor legal',payer:'Plătitor operațional',version:'Versiune',formula:'Formulă',evidence:'Dovadă',reason:'Motiv',details:'Detalii',close:'Închide',readonly:'Dovezi financiare doar pentru citire'},
 fa:{title:'تسهیم هزینه و حقوق مالی',sub:'شواهد نسخه‌دار و قابل توضیح با تفکیک مسئولیت مالک و مستأجر.',runs:'دوره‌های محاسبه',rules:'قواعد',lines:'ردیف‌های تسهیم',search:'جستجوی دسته، سند یا دوره',all:'همه',method:'روش',status:'وضعیت',from:'از',to:'تا',loading:'در حال دریافت تسهیم‌های مجاز…',empty:'در این زمینه تسهیمی قابل مشاهده نیست.',error:'دریافت اطلاعات تسهیم ناموفق بود.',refresh:'بازخوانی',source:'منبع',allocated:'تسهیم‌شده',difference:'اختلاف',period:'دوره',category:'دسته هزینه',basis:'مبنای محاسبه',share:'سهم',amount:'مبلغ',debtor:'مدیون قانونی',payer:'پرداخت‌کننده عملیاتی',version:'نسخه',formula:'فرمول',evidence:'مدرک',reason:'دلیل',details:'جزئیات',close:'بستن',readonly:'شواهد مالی فقط خواندنی'}
} as const;
type Labels=typeof copy.en|typeof copy.ro|typeof copy.fa;
const money=(v:unknown,c:unknown,lang:string)=>new Intl.NumberFormat(lang==='fa'?'fa-IR':lang==='ro'?'ro-RO':'en-US',{style:'currency',currency:String(c||'RON'),maximumFractionDigits:4}).format(Number(v||0));
const date=(v:unknown,lang:string)=>v?new Intl.DateTimeFormat(lang==='fa'?'fa-IR':lang==='ro'?'ro-RO':'en-US').format(new Date(String(v))):'—';
const text=(v:unknown)=>v==null||v===''?'—':String(v);

export function CustomerAllocationDashboard({lang}:{lang:string}){
 const t=copy[lang==='fa'?'fa':lang==='ro'?'ro':'en'];const{active}=useCustomerContext();
 const[view,setView]=useState<View>('runs'),[data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[offset,setOffset]=useState(0);
 const[draft,setDraft]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[method,setMethod]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[selected,setSelected]=useState<Record<string,unknown>|null>(null);
 const load=useCallback(async()=>{if(!active){setLoading(false);setData(null);return}setLoading(true);setError('');try{const p=new URLSearchParams({context_id:active.context_id,view,limit:'20',offset:String(offset)});if(query)p.set('query',query);if(status)p.set('status',status);if(method)p.set('method',method);if(from)p.set('from',from);if(to)p.set('to',to);const r=await fetch(`/api/customer/v1/allocations?${p}`,{cache:'no-store',credentials:'same-origin'});if(!r.ok)throw new Error();setData(await r.json())}catch{setError(t.error)}finally{setLoading(false)}},[active,view,offset,query,status,method,from,to,t.error]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),250);return()=>clearTimeout(timer)},[load]);
 function changeView(v:View){setView(v);setOffset(0);setStatus('');setMethod('');setSelected(null)}
 const statuses=view==='rules'?['active','inactive']:['draft','calculated','approved','posted','cancelled'];
 return <div className="space-y-5"><header className="rounded-2xl border border-[#D3DCE6] bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-[#0E9F8E]"><Scale className="h-4 w-4"/>C02 · Financial rights</div><h1 className="mt-1 text-2xl font-extrabold text-[#102A43]">{t.title}</h1><p className="mt-1 text-sm text-[#52667A]">{t.sub}</p></div><div className="rounded-xl border border-[#B2E5DF] bg-[#EAF8F5] px-3 py-2 text-xs font-bold text-[#0A6E62]"><ShieldCheck className="me-2 inline h-4 w-4"/>{t.readonly}</div></div></header>
 <div className="flex flex-wrap gap-2">{(['runs','rules','lines'] as View[]).map(v=><button key={v} onClick={()=>changeView(v)} className={`rounded-xl px-4 py-2 text-sm font-bold ${view===v?'bg-[#0E9F8E] text-white':'border bg-white text-[#334E68]'}`}>{t[v]}</button>)}</div>
 <form onSubmit={e=>{e.preventDefault();setOffset(0);setQuery(draft.trim())}} className="grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-6"><label className="relative md:col-span-2"><Search className="absolute start-3 top-2.5 h-4 w-4 text-[#7B8A9A]"/><span className="sr-only">{t.search}</span><input value={draft} onChange={e=>setDraft(e.target.value)} placeholder={t.search} className="w-full rounded-xl border py-2 pe-3 ps-9 text-sm"/></label><select aria-label={t.status} value={status} onChange={e=>{setStatus(e.target.value);setOffset(0)}} className="rounded-xl border px-3 py-2 text-sm"><option value="">{t.all} · {t.status}</option>{statuses.map(x=><option key={x}>{x}</option>)}</select><select aria-label={t.method} value={method} onChange={e=>{setMethod(e.target.value);setOffset(0)}} disabled={view==='runs'} className="rounded-xl border px-3 py-2 text-sm disabled:opacity-50"><option value="">{t.all} · {t.method}</option>{['meter_consumption','cpi','per_person','surface_m2','direct','fixed'].map(x=><option key={x}>{x}</option>)}</select><input type="date" aria-label={t.from} value={from} onChange={e=>{setFrom(e.target.value);setOffset(0)}} className="rounded-xl border px-3 py-2 text-sm"/><div className="flex gap-2"><input type="date" aria-label={t.to} value={to} onChange={e=>{setTo(e.target.value);setOffset(0)}} className="min-w-0 flex-1 rounded-xl border px-3 py-2 text-sm"/><button type="button" aria-label={t.refresh} onClick={()=>void load()} className="rounded-xl border p-2"><RefreshCw className="h-4 w-4"/></button></div></form>
 {data?.summary?.length?<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{data.summary.map(s=><article key={s.currency} className="rounded-2xl border bg-white p-4"><div className="text-xs font-bold text-[#52667A]">{s.currency} · {s.run_count} {t.runs}</div><div className="mt-2 text-lg font-extrabold text-[#102A43]">{money(s.allocated_amount,s.currency,lang)}</div><div className="mt-1 text-xs text-[#52667A]">{t.source}: {money(s.source_amount,s.currency,lang)} · {t.difference}: {money(s.difference,s.currency,lang)}</div></article>)}</div>:null}
 {loading?<Box value={t.loading}/>:error?<Box value={error}/>:!data?.rows.length?<Box value={t.empty}/>:<><div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[920px] text-start text-xs"><thead className="bg-[#F6F9FC] text-[#52667A]"><tr>{headers(view,t).map(h=><th key={h} className="p-3 text-start">{h}</th>)}</tr></thead><tbody className="divide-y">{data.rows.map(r=><tr key={String(r.id)} className="hover:bg-[#F6F9FC]"><Row view={view} row={r} lang={lang} t={t}/><td className="p-3"><button onClick={()=>setSelected(r)} className="font-bold text-[#087A6E]">{t.details}</button></td></tr>)}</tbody></table></div><div className="flex items-center justify-between text-xs text-[#52667A]"><span>{offset+1}–{Math.min(offset+20,data.total)} / {data.total}</span><div className="flex gap-2"><button disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-20))} className="rounded-xl border bg-white p-2 disabled:opacity-40"><ChevronLeft className="h-4 w-4 rtl:rotate-180"/></button><button disabled={offset+20>=data.total} onClick={()=>setOffset(offset+20)} className="rounded-xl border bg-white p-2 disabled:opacity-40"><ChevronRight className="h-4 w-4 rtl:rotate-180"/></button></div></div></>}
 {selected?<Detail row={selected} t={t} close={()=>setSelected(null)}/>:null}</div>
}
function headers(v:View,t:Labels){return v==='runs'?[t.period,t.status,t.source,t.allocated,t.difference,t.details]:v==='rules'?[t.category,t.method,t.version,t.period,t.status,t.details]:[t.category,t.source,t.method,t.basis,t.share,t.amount,t.debtor,t.details]}
function Row({view,row:r,lang,t}:{view:View;row:Record<string,unknown>;lang:string;t:Labels}){if(view==='runs')return <><td className="p-3">{date(r.period_start,lang)} → {date(r.period_end,lang)}</td><td className="p-3">{text(r.status)}</td><td className="p-3">{money(r.source_amount,r.currency,lang)}</td><td className="p-3 font-bold">{money(r.allocated_amount,r.currency,lang)}</td><td className="p-3">{money(r.difference,r.currency,lang)}</td></>;if(view==='rules')return <><td className="p-3 font-bold">{text(r.category_name)}</td><td className="p-3">{text(r.method)}</td><td className="p-3">v{text(r.version)}</td><td className="p-3">{date(r.valid_from,lang)} → {date(r.valid_to,lang)}</td><td className="p-3">{text(r.status)}</td></>;return <><td className="p-3 font-bold">{text(r.category_name)}</td><td className="p-3 font-mono">{text(r.source_document||r.source_id)}</td><td className="p-3">{text(r.method)}</td><td className="p-3">{text(r.basis_value)} / {text(r.basis_total)}</td><td className="p-3">{new Intl.NumberFormat(lang,{style:'percent',maximumFractionDigits:4}).format(Number(r.share_ratio||0))}</td><td className="p-3 font-bold">{money(r.allocated_amount,r.currency,lang)}</td><td className="p-3">{text(r.legal_debtor)}</td></>}
function Box({value}:{value:string}){return <div className="rounded-2xl border bg-white p-10 text-center text-sm text-[#52667A]">{value}</div>}
function Detail({row:r,t,close}:{row:Record<string,unknown>;t:Labels;close:()=>void}){const rule=(r.rule_snapshot??{}) as Record<string,unknown>,ex=(r.explanation??{}) as Record<string,unknown>;return <div role="dialog" aria-modal="true" className="fixed inset-0 z-[80] grid place-items-center bg-black/60 p-4"><div className="max-h-[85vh] w-full max-w-2xl overflow-auto rounded-2xl bg-white p-6"><div className="flex justify-between"><h2 className="font-extrabold text-[#102A43]">{t.details}</h2><button onClick={close} aria-label={t.close}><X/></button></div><dl className="mt-5 grid gap-4 text-sm sm:grid-cols-2"><Item k={t.formula} v={rule.formula}/><Item k={t.version} v={rule.version}/><Item k={t.debtor} v={r.legal_debtor??ex.legal_debtor}/><Item k={t.payer} v={r.operational_payer??ex.operational_payer}/><Item k={t.evidence} v={ex.evidence}/><Item k={t.reason} v={ex.reason}/></dl></div></div>}
function Item({k,v}:{k:string;v:unknown}){return <div className="rounded-xl bg-[#F6F9FC] p-3"><dt className="text-xs font-bold text-[#52667A]">{k}</dt><dd className="mt-1 break-words text-[#102A43]">{typeof v==='object'?JSON.stringify(v):text(v)}</dd></div>}
