"use client";
import { useCallback, useEffect, useState } from "react";
import { BadgeCheck, ChevronLeft, ChevronRight, DoorOpen, RefreshCw, Search, ShieldCheck, X } from "lucide-react";
import type { Language } from "@/types";
import { useCustomerContext } from "./CustomerContextProvider";

export type SecurityView="access_points"|"credentials"|"visitors"|"access_logs"|"credential_history"|"visitor_history"|"links";
type Row=Record<string,unknown>&{id?:string};
type Payload={rows:Row[];total:number;summary?:Record<string,number>;read_only:boolean;credential_data_masked:boolean;physical_control:boolean};
const copy={
 en:{title:"Security access registry",sub:"Authorized access points, masked credentials, visitor passes and immutable access history.",search:"Search authorized access records",status:"Status / decision",all:"All types",refresh:"Refresh",loading:"Loading authorized security records…",empty:"No security access records are visible in this context.",error:"The security access registry could not be loaded.",readonly:"Read-only · credentials masked · no door control",details:"Details",close:"Close",access_points:"Access points",credentials:"Credentials",visitors:"Visitors",access_logs:"Access logs",credential_history:"Credential lifecycle",visitor_history:"Visitor history",links:"Related records",points:"Access points",active_credentials:"Active credentials",valid_visitors:"Valid visitor passes",recent_denied:"Denied · 24h",previous:"Previous",next:"Next"},
 ro:{title:"Registru acces de securitate",sub:"Puncte de acces autorizate, credențiale mascate, permise pentru vizitatori și istoric imuabil.",search:"Caută înregistrări de acces autorizate",status:"Stare / decizie",all:"Toate tipurile",refresh:"Reîncarcă",loading:"Se încarcă înregistrările autorizate…",empty:"Nu există înregistrări de acces vizibile în acest context.",error:"Registrul de acces nu a putut fi încărcat.",readonly:"Doar citire · credențiale mascate · fără control uși",details:"Detalii",close:"Închide",access_points:"Puncte de acces",credentials:"Credențiale",visitors:"Vizitatori",access_logs:"Jurnale de acces",credential_history:"Ciclu credențiale",visitor_history:"Istoric vizitatori",links:"Înregistrări asociate",points:"Puncte de acces",active_credentials:"Credențiale active",valid_visitors:"Permise valabile",recent_denied:"Respins · 24h",previous:"Anterior",next:"Următor"},
 fa:{title:"دفتر دسترسی امنیتی",sub:"نقاط دسترسی مجاز، شناسه‌های پوشانده‌شده، مجوزهای بازدید و تاریخچه تغییرناپذیر ورود.",search:"جستجو در سوابق مجاز دسترسی",status:"وضعیت / نتیجه",all:"همه انواع",refresh:"بازخوانی",loading:"در حال دریافت سوابق امنیتی مجاز…",empty:"در این زمینه رکورد دسترسی قابل مشاهده‌ای نیست.",error:"دریافت دفتر دسترسی امنیتی ناموفق بود.",readonly:"فقط خواندنی · شناسه‌ها پوشانده · بدون کنترل در",details:"جزئیات",close:"بستن",access_points:"نقاط دسترسی",credentials:"شناسه‌ها و کلیدها",visitors:"بازدیدکنندگان",access_logs:"گزارش ورود",credential_history:"چرخه عمر شناسه",visitor_history:"تاریخچه بازدید",links:"سوابق مرتبط",points:"نقاط دسترسی",active_credentials:"شناسه فعال",valid_visitors:"مجوز معتبر",recent_denied:"ردشده · ۲۴ ساعت",previous:"قبلی",next:"بعدی"},
}as const;
const views:SecurityView[]=["access_points","credentials","visitors","access_logs","credential_history","visitor_history","links"];
const hidden=new Set(["id","party_id","unit_id","credential_id","visitor_pass_id","identifier_hash"]);
function show(value:unknown){if(value===null||value===undefined||value==="")return"—";if(typeof value==="boolean")return value?"✓":"—";if(typeof value==="object")return JSON.stringify(value);return String(value).replace("T"," ").replace(/\.\d{3}Z$/, " UTC");}
function dateTime(value:string){return value?`${value}T00:00:00Z`:"";}

export function CustomerSecurityAccessDashboard({lang,initialView="access_points"}:{lang:Language;initialView?:SecurityView}){
 const{active}=useCustomerContext(),t=copy[lang];
 const[view,setView]=useState<SecurityView>(initialView),[query,setQuery]=useState(""),[status,setStatus]=useState(""),[kind,setKind]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[offset,setOffset]=useState(0),[data,setData]=useState<Payload|null>(null),[selected,setSelected]=useState<Row|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=useCallback(async()=>{if(!active){setLoading(false);setData(null);return;}setLoading(true);setError("");try{const p=new URLSearchParams({context_id:active.context_id,view,limit:"20",offset:String(offset)});if(query)p.set("query",query);if(status)p.set("status",status);if(kind)p.set("kind",kind);if(from)p.set("from",dateTime(from));if(to)p.set("to",`${to}T23:59:59Z`);const response=await fetch(`/api/customer/v1/security-access?${p}`,{cache:"no-store",credentials:"same-origin"});if(!response.ok)throw new Error();setData(await response.json()as Payload);}catch{setError(t.error);}finally{setLoading(false);}},[active,view,offset,query,status,kind,from,to,t.error]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),150);return()=>clearTimeout(timer);},[load]);
 const summary=data?.summary??{};
 return <div className="space-y-5" dir={lang==="fa"?"rtl":"ltr"}>
  <header className="card-proptech border border-[#D3DCE6] bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-[#0E9F8E]"><ShieldCheck className="h-4 w-4"/>CLADORA · Security access</div><h1 className="mt-1 text-2xl font-extrabold text-[#102A43]">{t.title}</h1><p className="mt-1 max-w-3xl text-xs text-[#52667A]">{t.sub}</p></div><span className="rounded-full border border-[#B2E5DF] bg-[#EAF8F5] px-3 py-1 text-[11px] font-bold text-[#0A6E62]">{t.readonly}</span></div></header>
  <section className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[[t.points,summary.access_points??0],[t.active_credentials,summary.active_credentials??0],[t.valid_visitors,summary.valid_visitors??0],[t.recent_denied,summary.recent_denied??0]].map(([label,value])=><div key={String(label)} className="card-proptech bg-white p-4"><div className="text-[11px] text-[#52667A]">{label}</div><div className="mt-1 text-xl font-extrabold">{value}</div></div>)}</section>
  <section className="card-proptech overflow-hidden bg-white"><div className="flex gap-1 overflow-x-auto border-b p-2">{views.map(item=><button type="button" key={item} onClick={()=>{setView(item);setOffset(0);setSelected(null);setKind("");}} className={`whitespace-nowrap rounded-lg px-3 py-2 text-xs font-bold ${view===item?"bg-[#0E9F8E] text-white":"text-[#52667A] hover:bg-[#F6F9FC]"}`}>{t[item]}</button>)}</div>
   <div className="grid gap-2 border-b p-3 md:grid-cols-6"><label className="relative md:col-span-2"><Search className="absolute start-3 top-2.5 h-4 w-4 text-[#7B8A9A]"/><input value={query} onChange={e=>{setQuery(e.target.value);setOffset(0);}} placeholder={t.search} className="w-full rounded-lg border py-2 pe-3 ps-9 text-xs"/></label><input value={status} onChange={e=>{setStatus(e.target.value);setOffset(0);}} placeholder={t.status} className="rounded-lg border px-3 py-2 text-xs"/><select value={kind} onChange={e=>{setKind(e.target.value);setOffset(0);}} className="rounded-lg border px-3 py-2 text-xs"><option value="">{t.all}</option>{["entrance","door","gate","key","fob","access_card","visitor","contractor","delivery","vehicle"].map(x=><option value={x} key={x}>{x.replaceAll("_"," ")}</option>)}</select><input aria-label="From" type="date" value={from} onChange={e=>setFrom(e.target.value)} className="rounded-lg border px-2 py-2 text-xs"/><div className="flex gap-2"><input aria-label="To" type="date" value={to} onChange={e=>setTo(e.target.value)} className="min-w-0 flex-1 rounded-lg border px-2 py-2 text-xs"/><button type="button" onClick={()=>void load()} aria-label={t.refresh} className="rounded-lg border p-2"><RefreshCw className={`h-4 w-4 ${loading?"animate-spin":""}`}/></button></div></div>
   {loading?<div className="p-10 text-center text-xs text-[#52667A]">{t.loading}</div>:error?<div role="alert" className="p-10 text-center text-xs font-bold text-red-700">{error}</div>:!data?.rows.length?<div className="p-10 text-center text-xs text-[#52667A]"><DoorOpen className="mx-auto mb-2 h-7 w-7"/>{t.empty}</div>:<div className="divide-y">{data.rows.map((row,index)=>{const entries=Object.entries(row).filter(([key])=>!hidden.has(key)).slice(0,7);return <article key={row.id??`${view}-${index}`} className="flex items-center gap-3 p-4"><div className="rounded-xl bg-[#EAF8F5] p-2 text-[#0E9F8E]"><BadgeCheck className="h-5 w-5"/></div><div className="min-w-0 flex-1"><div className="truncate text-xs font-bold">{show(row.name??row.masked_identifier??row.visitor_label??row.access_point??row.visitor_pass??`#${index+1}`)}</div><div className="mt-1 flex flex-wrap gap-x-3 gap-y-1 text-[10px] text-[#64748B]">{entries.slice(1).map(([key,value])=><span key={key}><b>{key.replaceAll("_"," ")}:</b> {show(value)}</span>)}</div></div><button type="button" onClick={()=>setSelected(row)} className="rounded-lg border px-3 py-2 text-[11px] font-bold">{t.details}</button></article>;})}</div>}
   <div className="flex items-center justify-between border-t p-3 text-xs"><button type="button" disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-20))} className="flex items-center gap-1 rounded-lg border px-3 py-2 disabled:opacity-40"><ChevronLeft className="h-4 w-4"/>{t.previous}</button><span>{offset+1}–{Math.min(offset+20,data?.total??0)} / {data?.total??0}</span><button type="button" disabled={offset+20>=(data?.total??0)} onClick={()=>setOffset(offset+20)} className="flex items-center gap-1 rounded-lg border px-3 py-2 disabled:opacity-40">{t.next}<ChevronRight className="h-4 w-4"/></button></div>
  </section>
  {selected?<div className="fixed inset-0 z-50 flex items-end justify-end bg-[#102A43]/35 p-4" role="dialog" aria-modal="true"><div className="max-h-[85vh] w-full max-w-xl overflow-auto rounded-2xl bg-white p-5 shadow-xl"><div className="flex items-center justify-between"><h2 className="font-bold">{t.details}</h2><button type="button" onClick={()=>setSelected(null)} aria-label={t.close}><X className="h-5 w-5"/></button></div><dl className="mt-4 grid gap-3 sm:grid-cols-2">{Object.entries(selected).filter(([key])=>!hidden.has(key)).map(([key,value])=><div key={key} className="rounded-xl bg-[#F6F9FC] p-3"><dt className="text-[10px] font-bold uppercase text-[#64748B]">{key.replaceAll("_"," ")}</dt><dd className="mt-1 break-words text-xs">{show(value)}</dd></div>)}</dl></div></div>:null}
 </div>;
}
